-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Wed Apr  8 11:14:32 2026
-- Host        : eslpc53 running 64-bit Ubuntu 20.04.3 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_mv_0_0_stub.vhdl
-- Design      : design_1_mv_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu7ev-ffvc1156-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    s_axi_control_bus_ARADDR : in STD_LOGIC_VECTOR ( 4 downto 0 );
    s_axi_control_bus_ARREADY : out STD_LOGIC;
    s_axi_control_bus_ARVALID : in STD_LOGIC;
    s_axi_control_bus_AWADDR : in STD_LOGIC_VECTOR ( 4 downto 0 );
    s_axi_control_bus_AWREADY : out STD_LOGIC;
    s_axi_control_bus_AWVALID : in STD_LOGIC;
    s_axi_control_bus_BREADY : in STD_LOGIC;
    s_axi_control_bus_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_bus_BVALID : out STD_LOGIC;
    s_axi_control_bus_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_bus_RREADY : in STD_LOGIC;
    s_axi_control_bus_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_bus_RVALID : out STD_LOGIC;
    s_axi_control_bus_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_bus_WREADY : out STD_LOGIC;
    s_axi_control_bus_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_bus_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_A_port_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_A_port_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_port_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_port_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_port_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_A_port_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_port_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_port_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_port_ARREADY : in STD_LOGIC;
    m_axi_A_port_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_port_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_port_ARVALID : out STD_LOGIC;
    m_axi_A_port_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_A_port_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_port_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_port_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_port_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_A_port_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_port_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_port_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_port_AWREADY : in STD_LOGIC;
    m_axi_A_port_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_port_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_port_AWVALID : out STD_LOGIC;
    m_axi_A_port_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_port_BREADY : out STD_LOGIC;
    m_axi_A_port_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_port_BVALID : in STD_LOGIC;
    m_axi_A_port_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_A_port_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_port_RLAST : in STD_LOGIC;
    m_axi_A_port_RREADY : out STD_LOGIC;
    m_axi_A_port_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_port_RVALID : in STD_LOGIC;
    m_axi_A_port_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_A_port_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_port_WLAST : out STD_LOGIC;
    m_axi_A_port_WREADY : in STD_LOGIC;
    m_axi_A_port_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_port_WVALID : out STD_LOGIC;
    m_axi_b_port_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_b_port_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_port_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_port_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_port_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_b_port_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_port_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_port_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_port_ARREADY : in STD_LOGIC;
    m_axi_b_port_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_port_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_port_ARVALID : out STD_LOGIC;
    m_axi_b_port_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_b_port_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_port_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_port_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_port_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_b_port_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_port_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_port_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_port_AWREADY : in STD_LOGIC;
    m_axi_b_port_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_port_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_b_port_AWVALID : out STD_LOGIC;
    m_axi_b_port_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_port_BREADY : out STD_LOGIC;
    m_axi_b_port_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_port_BVALID : in STD_LOGIC;
    m_axi_b_port_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_b_port_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_port_RLAST : in STD_LOGIC;
    m_axi_b_port_RREADY : out STD_LOGIC;
    m_axi_b_port_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_b_port_RVALID : in STD_LOGIC;
    m_axi_b_port_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_b_port_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_b_port_WLAST : out STD_LOGIC;
    m_axi_b_port_WREADY : in STD_LOGIC;
    m_axi_b_port_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_b_port_WVALID : out STD_LOGIC;
    m_axi_c_port_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_c_port_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_c_port_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_c_port_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_c_port_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_c_port_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_c_port_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_c_port_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_c_port_ARREADY : in STD_LOGIC;
    m_axi_c_port_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_c_port_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_c_port_ARVALID : out STD_LOGIC;
    m_axi_c_port_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_c_port_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_c_port_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_c_port_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_c_port_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_c_port_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_c_port_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_c_port_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_c_port_AWREADY : in STD_LOGIC;
    m_axi_c_port_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_c_port_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_c_port_AWVALID : out STD_LOGIC;
    m_axi_c_port_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_c_port_BREADY : out STD_LOGIC;
    m_axi_c_port_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_c_port_BVALID : in STD_LOGIC;
    m_axi_c_port_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_c_port_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_c_port_RLAST : in STD_LOGIC;
    m_axi_c_port_RREADY : out STD_LOGIC;
    m_axi_c_port_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_c_port_RVALID : in STD_LOGIC;
    m_axi_c_port_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_c_port_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_c_port_WLAST : out STD_LOGIC;
    m_axi_c_port_WREADY : in STD_LOGIC;
    m_axi_c_port_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_c_port_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_mv_0_0,mv,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_mv_0_0,mv,{x_ipProduct=Vivado 2024.2,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=mv,x_ipVersion=1.0,x_ipCoreRevision=2114556464,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=6,C_S_AXI_CONTROL_DATA_WIDTH=32,C_S_AXI_CONTROL_BUS_ADDR_WIDTH=5,C_S_AXI_CONTROL_BUS_DATA_WIDTH=32,C_M_AXI_A_PORT_ID_WIDTH=1,C_M_AXI_A_PORT_ADDR_WIDTH=64,C_M_AXI_A_PORT_DATA_WIDTH=32,C_M_AXI_A_PORT_AWUSER_WIDTH=1,C_M_AXI_A_PORT_ARUSER_WIDTH=1,C_M_AXI_A_PORT_WUSER_WIDTH=1,C_M_AXI_A_PORT_RUSER_WIDTH=1,C_M_AXI_A_PORT_BUSER_WIDTH=1,C_M_AXI_A_PORT_USER_VALUE=0x00000000,C_M_AXI_A_PORT_PROT_VALUE=000,C_M_AXI_A_PORT_CACHE_VALUE=0011,C_M_AXI_B_PORT_ID_WIDTH=1,C_M_AXI_B_PORT_ADDR_WIDTH=64,C_M_AXI_B_PORT_DATA_WIDTH=32,C_M_AXI_B_PORT_AWUSER_WIDTH=1,C_M_AXI_B_PORT_ARUSER_WIDTH=1,C_M_AXI_B_PORT_WUSER_WIDTH=1,C_M_AXI_B_PORT_RUSER_WIDTH=1,C_M_AXI_B_PORT_BUSER_WIDTH=1,C_M_AXI_B_PORT_USER_VALUE=0x00000000,C_M_AXI_B_PORT_PROT_VALUE=000,C_M_AXI_B_PORT_CACHE_VALUE=0011,C_M_AXI_C_PORT_ID_WIDTH=1,C_M_AXI_C_PORT_ADDR_WIDTH=64,C_M_AXI_C_PORT_DATA_WIDTH=32,C_M_AXI_C_PORT_AWUSER_WIDTH=1,C_M_AXI_C_PORT_ARUSER_WIDTH=1,C_M_AXI_C_PORT_WUSER_WIDTH=1,C_M_AXI_C_PORT_RUSER_WIDTH=1,C_M_AXI_C_PORT_BUSER_WIDTH=1,C_M_AXI_C_PORT_USER_VALUE=0x00000000,C_M_AXI_C_PORT_PROT_VALUE=000,C_M_AXI_C_PORT_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,s_axi_control_bus_ARADDR[4:0],s_axi_control_bus_ARREADY,s_axi_control_bus_ARVALID,s_axi_control_bus_AWADDR[4:0],s_axi_control_bus_AWREADY,s_axi_control_bus_AWVALID,s_axi_control_bus_BREADY,s_axi_control_bus_BRESP[1:0],s_axi_control_bus_BVALID,s_axi_control_bus_RDATA[31:0],s_axi_control_bus_RREADY,s_axi_control_bus_RRESP[1:0],s_axi_control_bus_RVALID,s_axi_control_bus_WDATA[31:0],s_axi_control_bus_WREADY,s_axi_control_bus_WSTRB[3:0],s_axi_control_bus_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_A_port_ARADDR[63:0],m_axi_A_port_ARBURST[1:0],m_axi_A_port_ARCACHE[3:0],m_axi_A_port_ARID[0:0],m_axi_A_port_ARLEN[7:0],m_axi_A_port_ARLOCK[1:0],m_axi_A_port_ARPROT[2:0],m_axi_A_port_ARQOS[3:0],m_axi_A_port_ARREADY,m_axi_A_port_ARREGION[3:0],m_axi_A_port_ARSIZE[2:0],m_axi_A_port_ARVALID,m_axi_A_port_AWADDR[63:0],m_axi_A_port_AWBURST[1:0],m_axi_A_port_AWCACHE[3:0],m_axi_A_port_AWID[0:0],m_axi_A_port_AWLEN[7:0],m_axi_A_port_AWLOCK[1:0],m_axi_A_port_AWPROT[2:0],m_axi_A_port_AWQOS[3:0],m_axi_A_port_AWREADY,m_axi_A_port_AWREGION[3:0],m_axi_A_port_AWSIZE[2:0],m_axi_A_port_AWVALID,m_axi_A_port_BID[0:0],m_axi_A_port_BREADY,m_axi_A_port_BRESP[1:0],m_axi_A_port_BVALID,m_axi_A_port_RDATA[31:0],m_axi_A_port_RID[0:0],m_axi_A_port_RLAST,m_axi_A_port_RREADY,m_axi_A_port_RRESP[1:0],m_axi_A_port_RVALID,m_axi_A_port_WDATA[31:0],m_axi_A_port_WID[0:0],m_axi_A_port_WLAST,m_axi_A_port_WREADY,m_axi_A_port_WSTRB[3:0],m_axi_A_port_WVALID,m_axi_b_port_ARADDR[63:0],m_axi_b_port_ARBURST[1:0],m_axi_b_port_ARCACHE[3:0],m_axi_b_port_ARID[0:0],m_axi_b_port_ARLEN[7:0],m_axi_b_port_ARLOCK[1:0],m_axi_b_port_ARPROT[2:0],m_axi_b_port_ARQOS[3:0],m_axi_b_port_ARREADY,m_axi_b_port_ARREGION[3:0],m_axi_b_port_ARSIZE[2:0],m_axi_b_port_ARVALID,m_axi_b_port_AWADDR[63:0],m_axi_b_port_AWBURST[1:0],m_axi_b_port_AWCACHE[3:0],m_axi_b_port_AWID[0:0],m_axi_b_port_AWLEN[7:0],m_axi_b_port_AWLOCK[1:0],m_axi_b_port_AWPROT[2:0],m_axi_b_port_AWQOS[3:0],m_axi_b_port_AWREADY,m_axi_b_port_AWREGION[3:0],m_axi_b_port_AWSIZE[2:0],m_axi_b_port_AWVALID,m_axi_b_port_BID[0:0],m_axi_b_port_BREADY,m_axi_b_port_BRESP[1:0],m_axi_b_port_BVALID,m_axi_b_port_RDATA[31:0],m_axi_b_port_RID[0:0],m_axi_b_port_RLAST,m_axi_b_port_RREADY,m_axi_b_port_RRESP[1:0],m_axi_b_port_RVALID,m_axi_b_port_WDATA[31:0],m_axi_b_port_WID[0:0],m_axi_b_port_WLAST,m_axi_b_port_WREADY,m_axi_b_port_WSTRB[3:0],m_axi_b_port_WVALID,m_axi_c_port_ARADDR[63:0],m_axi_c_port_ARBURST[1:0],m_axi_c_port_ARCACHE[3:0],m_axi_c_port_ARID[0:0],m_axi_c_port_ARLEN[7:0],m_axi_c_port_ARLOCK[1:0],m_axi_c_port_ARPROT[2:0],m_axi_c_port_ARQOS[3:0],m_axi_c_port_ARREADY,m_axi_c_port_ARREGION[3:0],m_axi_c_port_ARSIZE[2:0],m_axi_c_port_ARVALID,m_axi_c_port_AWADDR[63:0],m_axi_c_port_AWBURST[1:0],m_axi_c_port_AWCACHE[3:0],m_axi_c_port_AWID[0:0],m_axi_c_port_AWLEN[7:0],m_axi_c_port_AWLOCK[1:0],m_axi_c_port_AWPROT[2:0],m_axi_c_port_AWQOS[3:0],m_axi_c_port_AWREADY,m_axi_c_port_AWREGION[3:0],m_axi_c_port_AWSIZE[2:0],m_axi_c_port_AWVALID,m_axi_c_port_BID[0:0],m_axi_c_port_BREADY,m_axi_c_port_BRESP[1:0],m_axi_c_port_BVALID,m_axi_c_port_RDATA[31:0],m_axi_c_port_RID[0:0],m_axi_c_port_RLAST,m_axi_c_port_RREADY,m_axi_c_port_RRESP[1:0],m_axi_c_port_RVALID,m_axi_c_port_WDATA[31:0],m_axi_c_port_WID[0:0],m_axi_c_port_WLAST,m_axi_c_port_WREADY,m_axi_c_port_WSTRB[3:0],m_axi_c_port_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of s_axi_control_bus_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus ARADDR";
  attribute X_INTERFACE_MODE of s_axi_control_bus_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_control_bus_ARADDR : signal is "XIL_INTERFACENAME s_axi_control_bus, ADDR_WIDTH 5, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_bus_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_bus_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_bus_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_bus_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_bus_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_bus_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_bus_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_bus_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_bus_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_bus_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_bus_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_bus_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_bus_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_bus_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_bus_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_bus_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control_bus WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:s_axi_control_bus:m_axi_A_port:m_axi_b_port:m_axi_c_port, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARADDR";
  attribute X_INTERFACE_MODE of m_axi_A_port_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_A_port_ARADDR : signal is "XIL_INTERFACENAME m_axi_A_port, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARBURST";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARID";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARLEN";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARPROT";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARQOS";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARREADY";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARREGION";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_A_port_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port ARVALID";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWADDR";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWBURST";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWID";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWLEN";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWPROT";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWQOS";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWREADY";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWREGION";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_A_port_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port AWVALID";
  attribute X_INTERFACE_INFO of m_axi_A_port_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port BID";
  attribute X_INTERFACE_INFO of m_axi_A_port_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port BREADY";
  attribute X_INTERFACE_INFO of m_axi_A_port_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port BRESP";
  attribute X_INTERFACE_INFO of m_axi_A_port_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port BVALID";
  attribute X_INTERFACE_INFO of m_axi_A_port_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port RDATA";
  attribute X_INTERFACE_INFO of m_axi_A_port_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port RID";
  attribute X_INTERFACE_INFO of m_axi_A_port_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port RLAST";
  attribute X_INTERFACE_INFO of m_axi_A_port_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port RREADY";
  attribute X_INTERFACE_INFO of m_axi_A_port_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port RRESP";
  attribute X_INTERFACE_INFO of m_axi_A_port_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port RVALID";
  attribute X_INTERFACE_INFO of m_axi_A_port_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port WDATA";
  attribute X_INTERFACE_INFO of m_axi_A_port_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port WID";
  attribute X_INTERFACE_INFO of m_axi_A_port_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port WLAST";
  attribute X_INTERFACE_INFO of m_axi_A_port_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port WREADY";
  attribute X_INTERFACE_INFO of m_axi_A_port_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port WSTRB";
  attribute X_INTERFACE_INFO of m_axi_A_port_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_port WVALID";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARADDR";
  attribute X_INTERFACE_MODE of m_axi_b_port_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_b_port_ARADDR : signal is "XIL_INTERFACENAME m_axi_b_port, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARBURST";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARID";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARLEN";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARPROT";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARQOS";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARREADY";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARREGION";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_b_port_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port ARVALID";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWADDR";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWBURST";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWID";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWLEN";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWPROT";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWQOS";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWREADY";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWREGION";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_b_port_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port AWVALID";
  attribute X_INTERFACE_INFO of m_axi_b_port_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port BID";
  attribute X_INTERFACE_INFO of m_axi_b_port_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port BREADY";
  attribute X_INTERFACE_INFO of m_axi_b_port_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port BRESP";
  attribute X_INTERFACE_INFO of m_axi_b_port_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port BVALID";
  attribute X_INTERFACE_INFO of m_axi_b_port_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port RDATA";
  attribute X_INTERFACE_INFO of m_axi_b_port_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port RID";
  attribute X_INTERFACE_INFO of m_axi_b_port_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port RLAST";
  attribute X_INTERFACE_INFO of m_axi_b_port_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port RREADY";
  attribute X_INTERFACE_INFO of m_axi_b_port_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port RRESP";
  attribute X_INTERFACE_INFO of m_axi_b_port_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port RVALID";
  attribute X_INTERFACE_INFO of m_axi_b_port_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port WDATA";
  attribute X_INTERFACE_INFO of m_axi_b_port_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port WID";
  attribute X_INTERFACE_INFO of m_axi_b_port_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port WLAST";
  attribute X_INTERFACE_INFO of m_axi_b_port_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port WREADY";
  attribute X_INTERFACE_INFO of m_axi_b_port_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port WSTRB";
  attribute X_INTERFACE_INFO of m_axi_b_port_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_b_port WVALID";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARADDR";
  attribute X_INTERFACE_MODE of m_axi_c_port_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_c_port_ARADDR : signal is "XIL_INTERFACENAME m_axi_c_port, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARBURST";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARID";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARLEN";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARPROT";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARQOS";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARREADY";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARREGION";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_c_port_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port ARVALID";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWADDR";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWBURST";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWID";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWLEN";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWPROT";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWQOS";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWREADY";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWREGION";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_c_port_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port AWVALID";
  attribute X_INTERFACE_INFO of m_axi_c_port_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port BID";
  attribute X_INTERFACE_INFO of m_axi_c_port_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port BREADY";
  attribute X_INTERFACE_INFO of m_axi_c_port_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port BRESP";
  attribute X_INTERFACE_INFO of m_axi_c_port_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port BVALID";
  attribute X_INTERFACE_INFO of m_axi_c_port_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port RDATA";
  attribute X_INTERFACE_INFO of m_axi_c_port_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port RID";
  attribute X_INTERFACE_INFO of m_axi_c_port_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port RLAST";
  attribute X_INTERFACE_INFO of m_axi_c_port_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port RREADY";
  attribute X_INTERFACE_INFO of m_axi_c_port_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port RRESP";
  attribute X_INTERFACE_INFO of m_axi_c_port_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port RVALID";
  attribute X_INTERFACE_INFO of m_axi_c_port_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port WDATA";
  attribute X_INTERFACE_INFO of m_axi_c_port_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port WID";
  attribute X_INTERFACE_INFO of m_axi_c_port_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port WLAST";
  attribute X_INTERFACE_INFO of m_axi_c_port_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port WREADY";
  attribute X_INTERFACE_INFO of m_axi_c_port_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port WSTRB";
  attribute X_INTERFACE_INFO of m_axi_c_port_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_c_port WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "mv,Vivado 2024.2";
begin
end;
