// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module spmv_csc_read_nnz_packed (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        nnz,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        row_in,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        val_in,
        nnz_stream_din,
        nnz_stream_full_n,
        nnz_stream_write,
        nnz_stream_num_data_valid,
        nnz_stream_fifo_cap,
        nnz_c_din,
        nnz_c_full_n,
        nnz_c_write,
        nnz_c_num_data_valid,
        nnz_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] nnz;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [511:0] m_axi_gmem0_0_WDATA;
output  [63:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [511:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [8:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] row_in;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [511:0] m_axi_gmem2_0_WDATA;
output  [63:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [511:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [8:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [63:0] val_in;
output  [1031:0] nnz_stream_din;
input   nnz_stream_full_n;
output   nnz_stream_write;
input  [8:0] nnz_stream_num_data_valid;
input  [8:0] nnz_stream_fifo_cap;
output  [31:0] nnz_c_din;
input   nnz_c_full_n;
output   nnz_c_write;
input  [2:0] nnz_c_num_data_valid;
input  [2:0] nnz_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_0_ARVALID;
reg[63:0] m_axi_gmem0_0_ARADDR;
reg[0:0] m_axi_gmem0_0_ARID;
reg[31:0] m_axi_gmem0_0_ARLEN;
reg[2:0] m_axi_gmem0_0_ARSIZE;
reg[1:0] m_axi_gmem0_0_ARBURST;
reg[1:0] m_axi_gmem0_0_ARLOCK;
reg[3:0] m_axi_gmem0_0_ARCACHE;
reg[2:0] m_axi_gmem0_0_ARPROT;
reg[3:0] m_axi_gmem0_0_ARQOS;
reg[3:0] m_axi_gmem0_0_ARREGION;
reg[0:0] m_axi_gmem0_0_ARUSER;
reg m_axi_gmem0_0_RREADY;
reg m_axi_gmem2_0_ARVALID;
reg[63:0] m_axi_gmem2_0_ARADDR;
reg[0:0] m_axi_gmem2_0_ARID;
reg[31:0] m_axi_gmem2_0_ARLEN;
reg[2:0] m_axi_gmem2_0_ARSIZE;
reg[1:0] m_axi_gmem2_0_ARBURST;
reg[1:0] m_axi_gmem2_0_ARLOCK;
reg[3:0] m_axi_gmem2_0_ARCACHE;
reg[2:0] m_axi_gmem2_0_ARPROT;
reg[3:0] m_axi_gmem2_0_ARQOS;
reg[3:0] m_axi_gmem2_0_ARREGION;
reg[0:0] m_axi_gmem2_0_ARUSER;
reg m_axi_gmem2_0_RREADY;
reg nnz_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem2_blk_n_AR;
reg    nnz_c_blk_n;
reg   [31:0] nnz_read_reg_265;
reg    ap_block_state1;
wire   [28:0] words_fu_182_p3;
reg   [28:0] words_reg_270;
wire   [28:0] empty_fu_196_p3;
reg   [28:0] empty_reg_275;
wire  signed [57:0] trunc_ln2_fu_204_p4;
reg   [57:0] trunc_ln2_reg_280;
reg    ap_block_state2_io;
wire   [63:0] zext_ln89_fu_228_p1;
wire  signed [57:0] trunc_ln89_1_fu_234_p4;
reg   [57:0] trunc_ln89_1_reg_296;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_done;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_idle;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_ready;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWID;
wire   [31:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWUSER;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WVALID;
wire   [511:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WDATA;
wire   [63:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WSTRB;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WID;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WUSER;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARID;
wire   [31:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARUSER;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_RREADY;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_BREADY;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWVALID;
wire   [63:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWADDR;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWID;
wire   [31:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWLEN;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWSIZE;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWBURST;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWLOCK;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWCACHE;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWPROT;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWQOS;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWREGION;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWUSER;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WVALID;
wire   [511:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WDATA;
wire   [63:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WSTRB;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WLAST;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WID;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WUSER;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARVALID;
wire   [63:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARADDR;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARID;
wire   [31:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARLEN;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARSIZE;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARBURST;
wire   [1:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARLOCK;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARCACHE;
wire   [2:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARPROT;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARQOS;
wire   [3:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARREGION;
wire   [0:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARUSER;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_RREADY;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_BREADY;
wire   [1031:0] grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_nnz_stream_din;
wire    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_nnz_stream_write;
reg    grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [63:0] sext_ln89_fu_214_p1;
wire  signed [63:0] sext_ln89_2_fu_244_p1;
wire   [31:0] add_ln86_fu_128_p2;
wire   [31:0] sub_ln86_fu_142_p2;
wire   [27:0] tmp_fu_148_p4;
wire   [28:0] zext_ln86_fu_158_p1;
wire   [27:0] tmp_5_fu_168_p4;
wire   [0:0] tmp_7_fu_134_p3;
wire   [28:0] sub_ln86_1_fu_162_p2;
wire   [28:0] zext_ln86_1_fu_178_p1;
wire   [0:0] icmp_ln89_fu_190_p2;
wire  signed [31:0] sext_ln89_1_fu_225_p1;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start_reg = 1'b0;
end

spmv_csc_read_nnz_packed_Pipeline_VITIS_LOOP_89_1 grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start),
    .ap_done(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_done),
    .ap_idle(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_idle),
    .ap_ready(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(m_axi_gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(m_axi_gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(m_axi_gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(m_axi_gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(m_axi_gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(m_axi_gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(m_axi_gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(m_axi_gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .m_axi_gmem2_0_AWVALID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(m_axi_gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(m_axi_gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(m_axi_gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(m_axi_gmem2_0_RLAST),
    .m_axi_gmem2_0_RID(m_axi_gmem2_0_RID),
    .m_axi_gmem2_0_RFIFONUM(m_axi_gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(m_axi_gmem2_0_RUSER),
    .m_axi_gmem2_0_RRESP(m_axi_gmem2_0_RRESP),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .nnz_stream_din(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_nnz_stream_din),
    .nnz_stream_full_n(nnz_stream_full_n),
    .nnz_stream_write(grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_nnz_stream_write),
    .nnz_stream_num_data_valid(9'd0),
    .nnz_stream_fifo_cap(9'd0),
    .words(words_reg_270),
    .sext_ln89(trunc_ln2_reg_280),
    .sext_ln89_2(trunc_ln89_1_reg_296),
    .nnz(nnz_read_reg_265)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start_reg <= 1'b1;
        end else if ((grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_ready == 1'b1)) begin
            grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_reg_275 <= empty_fu_196_p3;
        nnz_read_reg_265 <= nnz;
        words_reg_270 <= words_fu_182_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        trunc_ln2_reg_280 <= {{row_in[63:6]}};
        trunc_ln89_1_reg_296 <= {{val_in[63:6]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem2_blk_n_AR = m_axi_gmem2_0_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        m_axi_gmem0_0_ARADDR = sext_ln89_fu_214_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARADDR = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARADDR;
    end else begin
        m_axi_gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARBURST = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARBURST;
    end else begin
        m_axi_gmem0_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARCACHE = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARCACHE;
    end else begin
        m_axi_gmem0_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARID = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARID;
    end else begin
        m_axi_gmem0_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        m_axi_gmem0_0_ARLEN = zext_ln89_fu_228_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARLEN = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARLEN;
    end else begin
        m_axi_gmem0_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARLOCK = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARLOCK;
    end else begin
        m_axi_gmem0_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARPROT = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARPROT;
    end else begin
        m_axi_gmem0_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARQOS = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARQOS;
    end else begin
        m_axi_gmem0_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARREGION = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARREGION;
    end else begin
        m_axi_gmem0_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARSIZE = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARSIZE;
    end else begin
        m_axi_gmem0_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARUSER = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARUSER;
    end else begin
        m_axi_gmem0_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARVALID = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_ARVALID;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_RREADY = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem0_0_RREADY;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        m_axi_gmem2_0_ARADDR = sext_ln89_2_fu_244_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARADDR = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARADDR;
    end else begin
        m_axi_gmem2_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARBURST = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARBURST;
    end else begin
        m_axi_gmem2_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARCACHE = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARCACHE;
    end else begin
        m_axi_gmem2_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARID = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARID;
    end else begin
        m_axi_gmem2_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        m_axi_gmem2_0_ARLEN = zext_ln89_fu_228_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARLEN = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARLEN;
    end else begin
        m_axi_gmem2_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARLOCK = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARLOCK;
    end else begin
        m_axi_gmem2_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARPROT = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARPROT;
    end else begin
        m_axi_gmem2_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARQOS = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARQOS;
    end else begin
        m_axi_gmem2_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARREGION = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARREGION;
    end else begin
        m_axi_gmem2_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARSIZE = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARSIZE;
    end else begin
        m_axi_gmem2_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARUSER = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARUSER;
    end else begin
        m_axi_gmem2_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        m_axi_gmem2_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_ARVALID = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_ARVALID;
    end else begin
        m_axi_gmem2_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem2_0_RREADY = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_m_axi_gmem2_0_RREADY;
    end else begin
        m_axi_gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nnz_c_blk_n = nnz_c_full_n;
    end else begin
        nnz_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        nnz_c_write = 1'b1;
    end else begin
        nnz_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln86_fu_128_p2 = (nnz + 32'd15);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | (nnz_c_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem0_0_ARREADY == 1'b0) | (m_axi_gmem2_0_ARREADY == 1'b0));
end

assign empty_fu_196_p3 = ((icmp_ln89_fu_190_p2[0:0] == 1'b1) ? words_fu_182_p3 : 29'd0);

assign grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_ap_start_reg;

assign icmp_ln89_fu_190_p2 = (($signed(nnz) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 512'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 64'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = 512'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 64'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign nnz_c_din = nnz;

assign nnz_stream_din = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_nnz_stream_din;

assign nnz_stream_write = grp_read_nnz_packed_Pipeline_VITIS_LOOP_89_1_fu_114_nnz_stream_write;

assign sext_ln89_1_fu_225_p1 = $signed(empty_reg_275);

assign sext_ln89_2_fu_244_p1 = trunc_ln89_1_fu_234_p4;

assign sext_ln89_fu_214_p1 = trunc_ln2_fu_204_p4;

assign sub_ln86_1_fu_162_p2 = (29'd0 - zext_ln86_fu_158_p1);

assign sub_ln86_fu_142_p2 = ($signed(32'd4294967281) - $signed(nnz));

assign tmp_5_fu_168_p4 = {{add_ln86_fu_128_p2[31:4]}};

assign tmp_7_fu_134_p3 = add_ln86_fu_128_p2[32'd31];

assign tmp_fu_148_p4 = {{sub_ln86_fu_142_p2[31:4]}};

assign trunc_ln2_fu_204_p4 = {{row_in[63:6]}};

assign trunc_ln89_1_fu_234_p4 = {{val_in[63:6]}};

assign words_fu_182_p3 = ((tmp_7_fu_134_p3[0:0] == 1'b1) ? sub_ln86_1_fu_162_p2 : zext_ln86_1_fu_178_p1);

assign zext_ln86_1_fu_178_p1 = tmp_5_fu_168_p4;

assign zext_ln86_fu_158_p1 = tmp_fu_148_p4;

assign zext_ln89_fu_228_p1 = $unsigned(sext_ln89_1_fu_225_p1);

endmodule //spmv_csc_read_nnz_packed
