

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_2_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_3_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_4_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_5_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_6_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.x_buf_7_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_1_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_2_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_3_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_4_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_5_U"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_6_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_7_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_x_buff_fu_248"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_x_buff_fu_248.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_col_loop_fu_264"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_col_loop_fu_264.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_mac_loop_fu_280"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_mac_loop_fu_280.fadd_32ns_32ns_32_4_full_dsp_1_U23"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_mac_loop_fu_280.fmul_32ns_32ns_32_3_max_dsp_1_U24"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_mac_loop_fu_280.sparsemux_17_3_32_1_1_U25"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_mac_loop_fu_280.sparsemux_17_3_32_1_1_U26"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mv_Pipeline_mac_loop_fu_280.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_bus_s_axi_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_port_m_axi_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.b_port_m_axi_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.c_port_m_axi_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32ns_32ns_63_1_1_U48"}]}
set DependenceCheckSize 0
