// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="spmv_csr_spmv_csr,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=5404,HLS_SYN_LUT=5707,HLS_VERSION=2024_2}" *)

module spmv_csr (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        m_axi_gmem4_AWVALID,
        m_axi_gmem4_AWREADY,
        m_axi_gmem4_AWADDR,
        m_axi_gmem4_AWID,
        m_axi_gmem4_AWLEN,
        m_axi_gmem4_AWSIZE,
        m_axi_gmem4_AWBURST,
        m_axi_gmem4_AWLOCK,
        m_axi_gmem4_AWCACHE,
        m_axi_gmem4_AWPROT,
        m_axi_gmem4_AWQOS,
        m_axi_gmem4_AWREGION,
        m_axi_gmem4_AWUSER,
        m_axi_gmem4_WVALID,
        m_axi_gmem4_WREADY,
        m_axi_gmem4_WDATA,
        m_axi_gmem4_WSTRB,
        m_axi_gmem4_WLAST,
        m_axi_gmem4_WID,
        m_axi_gmem4_WUSER,
        m_axi_gmem4_ARVALID,
        m_axi_gmem4_ARREADY,
        m_axi_gmem4_ARADDR,
        m_axi_gmem4_ARID,
        m_axi_gmem4_ARLEN,
        m_axi_gmem4_ARSIZE,
        m_axi_gmem4_ARBURST,
        m_axi_gmem4_ARLOCK,
        m_axi_gmem4_ARCACHE,
        m_axi_gmem4_ARPROT,
        m_axi_gmem4_ARQOS,
        m_axi_gmem4_ARREGION,
        m_axi_gmem4_ARUSER,
        m_axi_gmem4_RVALID,
        m_axi_gmem4_RREADY,
        m_axi_gmem4_RDATA,
        m_axi_gmem4_RLAST,
        m_axi_gmem4_RID,
        m_axi_gmem4_RUSER,
        m_axi_gmem4_RRESP,
        m_axi_gmem4_BVALID,
        m_axi_gmem4_BREADY,
        m_axi_gmem4_BRESP,
        m_axi_gmem4_BID,
        m_axi_gmem4_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 39'd1;
parameter    ap_ST_fsm_state2 = 39'd2;
parameter    ap_ST_fsm_state3 = 39'd4;
parameter    ap_ST_fsm_state4 = 39'd8;
parameter    ap_ST_fsm_state5 = 39'd16;
parameter    ap_ST_fsm_state6 = 39'd32;
parameter    ap_ST_fsm_state7 = 39'd64;
parameter    ap_ST_fsm_state8 = 39'd128;
parameter    ap_ST_fsm_state9 = 39'd256;
parameter    ap_ST_fsm_state10 = 39'd512;
parameter    ap_ST_fsm_state11 = 39'd1024;
parameter    ap_ST_fsm_state12 = 39'd2048;
parameter    ap_ST_fsm_state13 = 39'd4096;
parameter    ap_ST_fsm_state14 = 39'd8192;
parameter    ap_ST_fsm_state15 = 39'd16384;
parameter    ap_ST_fsm_state16 = 39'd32768;
parameter    ap_ST_fsm_state17 = 39'd65536;
parameter    ap_ST_fsm_state18 = 39'd131072;
parameter    ap_ST_fsm_state19 = 39'd262144;
parameter    ap_ST_fsm_state20 = 39'd524288;
parameter    ap_ST_fsm_state21 = 39'd1048576;
parameter    ap_ST_fsm_state22 = 39'd2097152;
parameter    ap_ST_fsm_state23 = 39'd4194304;
parameter    ap_ST_fsm_state24 = 39'd8388608;
parameter    ap_ST_fsm_state25 = 39'd16777216;
parameter    ap_ST_fsm_state26 = 39'd33554432;
parameter    ap_ST_fsm_state27 = 39'd67108864;
parameter    ap_ST_fsm_state28 = 39'd134217728;
parameter    ap_ST_fsm_state29 = 39'd268435456;
parameter    ap_ST_fsm_state30 = 39'd536870912;
parameter    ap_ST_fsm_state31 = 39'd1073741824;
parameter    ap_ST_fsm_state32 = 39'd2147483648;
parameter    ap_ST_fsm_state33 = 39'd4294967296;
parameter    ap_ST_fsm_state34 = 39'd8589934592;
parameter    ap_ST_fsm_state35 = 39'd17179869184;
parameter    ap_ST_fsm_state36 = 39'd34359738368;
parameter    ap_ST_fsm_state37 = 39'd68719476736;
parameter    ap_ST_fsm_state38 = 39'd137438953472;
parameter    ap_ST_fsm_state39 = 39'd274877906944;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM3_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM3_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_USER_VALUE = 0;
parameter    C_M_AXI_GMEM3_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM3_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM4_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM4_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM4_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM4_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM4_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM4_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM4_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM4_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM4_USER_VALUE = 0;
parameter    C_M_AXI_GMEM4_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM4_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM3_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM4_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_AWADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_AWID;
output  [7:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [C_M_AXI_GMEM3_AWUSER_WIDTH - 1:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_WDATA;
output  [C_M_AXI_GMEM3_WSTRB_WIDTH - 1:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_WID;
output  [C_M_AXI_GMEM3_WUSER_WIDTH - 1:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_ARADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_ARID;
output  [7:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [C_M_AXI_GMEM3_ARUSER_WIDTH - 1:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_RID;
input  [C_M_AXI_GMEM3_RUSER_WIDTH - 1:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_BID;
input  [C_M_AXI_GMEM3_BUSER_WIDTH - 1:0] m_axi_gmem3_BUSER;
output   m_axi_gmem4_AWVALID;
input   m_axi_gmem4_AWREADY;
output  [C_M_AXI_GMEM4_ADDR_WIDTH - 1:0] m_axi_gmem4_AWADDR;
output  [C_M_AXI_GMEM4_ID_WIDTH - 1:0] m_axi_gmem4_AWID;
output  [7:0] m_axi_gmem4_AWLEN;
output  [2:0] m_axi_gmem4_AWSIZE;
output  [1:0] m_axi_gmem4_AWBURST;
output  [1:0] m_axi_gmem4_AWLOCK;
output  [3:0] m_axi_gmem4_AWCACHE;
output  [2:0] m_axi_gmem4_AWPROT;
output  [3:0] m_axi_gmem4_AWQOS;
output  [3:0] m_axi_gmem4_AWREGION;
output  [C_M_AXI_GMEM4_AWUSER_WIDTH - 1:0] m_axi_gmem4_AWUSER;
output   m_axi_gmem4_WVALID;
input   m_axi_gmem4_WREADY;
output  [C_M_AXI_GMEM4_DATA_WIDTH - 1:0] m_axi_gmem4_WDATA;
output  [C_M_AXI_GMEM4_WSTRB_WIDTH - 1:0] m_axi_gmem4_WSTRB;
output   m_axi_gmem4_WLAST;
output  [C_M_AXI_GMEM4_ID_WIDTH - 1:0] m_axi_gmem4_WID;
output  [C_M_AXI_GMEM4_WUSER_WIDTH - 1:0] m_axi_gmem4_WUSER;
output   m_axi_gmem4_ARVALID;
input   m_axi_gmem4_ARREADY;
output  [C_M_AXI_GMEM4_ADDR_WIDTH - 1:0] m_axi_gmem4_ARADDR;
output  [C_M_AXI_GMEM4_ID_WIDTH - 1:0] m_axi_gmem4_ARID;
output  [7:0] m_axi_gmem4_ARLEN;
output  [2:0] m_axi_gmem4_ARSIZE;
output  [1:0] m_axi_gmem4_ARBURST;
output  [1:0] m_axi_gmem4_ARLOCK;
output  [3:0] m_axi_gmem4_ARCACHE;
output  [2:0] m_axi_gmem4_ARPROT;
output  [3:0] m_axi_gmem4_ARQOS;
output  [3:0] m_axi_gmem4_ARREGION;
output  [C_M_AXI_GMEM4_ARUSER_WIDTH - 1:0] m_axi_gmem4_ARUSER;
input   m_axi_gmem4_RVALID;
output   m_axi_gmem4_RREADY;
input  [C_M_AXI_GMEM4_DATA_WIDTH - 1:0] m_axi_gmem4_RDATA;
input   m_axi_gmem4_RLAST;
input  [C_M_AXI_GMEM4_ID_WIDTH - 1:0] m_axi_gmem4_RID;
input  [C_M_AXI_GMEM4_RUSER_WIDTH - 1:0] m_axi_gmem4_RUSER;
input  [1:0] m_axi_gmem4_RRESP;
input   m_axi_gmem4_BVALID;
output   m_axi_gmem4_BREADY;
input  [1:0] m_axi_gmem4_BRESP;
input  [C_M_AXI_GMEM4_ID_WIDTH - 1:0] m_axi_gmem4_BID;
input  [C_M_AXI_GMEM4_BUSER_WIDTH - 1:0] m_axi_gmem4_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [38:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] num_rows;
wire   [31:0] num_cols;
wire   [63:0] A_row_index;
wire   [63:0] A_col_index;
wire   [63:0] A_values;
wire   [63:0] x;
wire   [63:0] y;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state13;
reg    gmem0_blk_n_R;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_state24;
reg    gmem2_blk_n_AR;
reg    gmem3_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem4_blk_n_AW;
reg    gmem4_blk_n_W;
wire    ap_CS_fsm_state34;
reg    gmem4_blk_n_B;
wire    ap_CS_fsm_state39;
reg   [63:0] A_values_read_reg_502;
reg   [63:0] A_col_index_read_reg_507;
reg   [63:0] A_row_index_read_reg_512;
reg   [31:0] num_cols_read_reg_517;
reg   [31:0] num_rows_read_reg_522;
reg   [61:0] trunc_ln_reg_533;
wire   [30:0] empty_fu_268_p3;
reg   [30:0] empty_reg_539;
reg   [63:0] gmem4_addr_reg_544;
wire   [30:0] empty_29_fu_306_p3;
reg   [30:0] empty_29_reg_550;
wire   [63:0] zext_ln23_fu_329_p1;
reg   [63:0] gmem0_addr_reg_568;
wire    ap_CS_fsm_state12;
reg   [31:0] row_start_reg_574;
reg   [31:0] row_end_reg_582;
reg   [61:0] trunc_ln3_reg_589;
reg   [61:0] trunc_ln36_1_reg_595;
wire   [32:0] empty_32_fu_454_p3;
reg   [32:0] empty_32_reg_601;
wire    ap_CS_fsm_state23;
wire  signed [63:0] sext_ln36_4_fu_472_p1;
reg   [9:0] x_buf_address0;
reg    x_buf_ce0;
reg    x_buf_we0;
wire   [31:0] x_buf_q0;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_ap_done;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_ap_idle;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_ap_ready;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWVALID;
wire   [63:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWADDR;
wire   [0:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWID;
wire   [31:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWLEN;
wire   [2:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWSIZE;
wire   [1:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWBURST;
wire   [1:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWLOCK;
wire   [3:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWCACHE;
wire   [2:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWPROT;
wire   [3:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWQOS;
wire   [3:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWREGION;
wire   [0:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWUSER;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WVALID;
wire   [31:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WDATA;
wire   [3:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WSTRB;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WLAST;
wire   [0:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WID;
wire   [0:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WUSER;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARVALID;
wire   [63:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARADDR;
wire   [0:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARID;
wire   [31:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARLEN;
wire   [2:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARSIZE;
wire   [1:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARBURST;
wire   [1:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARLOCK;
wire   [3:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARCACHE;
wire   [2:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARPROT;
wire   [3:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARQOS;
wire   [3:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARREGION;
wire   [0:0] grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARUSER;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_RREADY;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_BREADY;
wire   [9:0] grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_address0;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_ce0;
wire    grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_we0;
wire   [31:0] grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_d0;
wire    grp_spmv_csr_Pipeline_L2_fu_234_ap_start;
wire    grp_spmv_csr_Pipeline_L2_fu_234_ap_done;
wire    grp_spmv_csr_Pipeline_L2_fu_234_ap_idle;
wire    grp_spmv_csr_Pipeline_L2_fu_234_ap_ready;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWVALID;
wire   [63:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWADDR;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWID;
wire   [31:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWLEN;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWSIZE;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWBURST;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWLOCK;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWCACHE;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWPROT;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWQOS;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWREGION;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWUSER;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WVALID;
wire   [31:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WDATA;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WSTRB;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WLAST;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WID;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WUSER;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARVALID;
wire   [63:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARADDR;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARID;
wire   [31:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARLEN;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARSIZE;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARBURST;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARLOCK;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARCACHE;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARPROT;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARQOS;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARREGION;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARUSER;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_RREADY;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_BREADY;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWID;
wire   [31:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWUSER;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WVALID;
wire   [31:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WDATA;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WSTRB;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WID;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WUSER;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARID;
wire   [31:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARUSER;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_RREADY;
wire    grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_BREADY;
wire   [9:0] grp_spmv_csr_Pipeline_L2_fu_234_x_buf_address0;
wire    grp_spmv_csr_Pipeline_L2_fu_234_x_buf_ce0;
wire   [31:0] grp_spmv_csr_Pipeline_L2_fu_234_sum_out;
wire    grp_spmv_csr_Pipeline_L2_fu_234_sum_out_ap_vld;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
wire   [31:0] gmem0_0_ARLEN;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [31:0] gmem0_0_RDATA;
wire   [8:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
reg    gmem1_0_ARVALID;
wire    gmem1_0_ARREADY;
reg   [63:0] gmem1_0_ARADDR;
reg   [31:0] gmem1_0_ARLEN;
wire    gmem1_0_RVALID;
reg    gmem1_0_RREADY;
wire   [31:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
wire    gmem2_0_AWREADY;
wire    gmem2_0_WREADY;
reg    gmem2_0_ARVALID;
wire    gmem2_0_ARREADY;
reg   [63:0] gmem2_0_ARADDR;
reg   [31:0] gmem2_0_ARLEN;
wire    gmem2_0_RVALID;
reg    gmem2_0_RREADY;
wire   [31:0] gmem2_0_RDATA;
wire   [8:0] gmem2_0_RFIFONUM;
wire    gmem2_0_BVALID;
wire    gmem3_0_AWREADY;
wire    gmem3_0_WREADY;
reg    gmem3_0_ARVALID;
wire    gmem3_0_ARREADY;
reg   [63:0] gmem3_0_ARADDR;
reg   [31:0] gmem3_0_ARLEN;
wire    gmem3_0_RVALID;
reg    gmem3_0_RREADY;
wire   [31:0] gmem3_0_RDATA;
wire   [8:0] gmem3_0_RFIFONUM;
wire    gmem3_0_BVALID;
reg    gmem4_0_AWVALID;
wire    gmem4_0_AWREADY;
wire   [31:0] gmem4_0_AWLEN;
reg    gmem4_0_WVALID;
wire    gmem4_0_WREADY;
wire   [31:0] gmem4_0_WDATA;
wire    gmem4_0_ARREADY;
wire    gmem4_0_RVALID;
wire   [31:0] gmem4_0_RDATA;
wire   [8:0] gmem4_0_RFIFONUM;
wire    gmem4_0_BVALID;
reg    gmem4_0_BREADY;
reg    grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_spmv_csr_Pipeline_L2_fu_234_ap_start_reg;
wire    ap_CS_fsm_state31;
reg   [38:0] ap_NS_fsm;
wire    ap_NS_fsm_state32;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state32;
wire  signed [63:0] sext_ln29_fu_296_p1;
wire  signed [63:0] sext_ln23_fu_319_p1;
wire  signed [63:0] sext_ln32_fu_382_p1;
wire   [0:0] icmp_ln29_1_fu_344_p2;
wire  signed [63:0] sext_ln36_1_fu_462_p1;
wire  signed [63:0] sext_ln36_2_fu_477_p1;
reg    ap_block_state2_io;
reg    ap_block_state24_io;
reg   [30:0] i_1_fu_126;
wire   [30:0] add_ln33_fu_349_p2;
wire   [0:0] icmp_ln23_fu_248_p2;
wire   [30:0] trunc_ln23_fu_254_p1;
wire   [61:0] trunc_ln1_fu_286_p4;
wire   [0:0] icmp_ln29_fu_276_p2;
wire   [30:0] trunc_ln29_fu_282_p1;
wire   [31:0] zext_ln29_1_fu_340_p1;
wire   [32:0] shl_ln_fu_355_p3;
wire   [63:0] zext_ln32_fu_363_p1;
wire   [63:0] add_ln32_fu_367_p2;
wire   [61:0] trunc_ln2_fu_372_p4;
wire   [33:0] shl_ln1_fu_397_p3;
wire  signed [63:0] sext_ln36_3_fu_404_p1;
wire   [63:0] add_ln36_fu_408_p2;
wire   [63:0] add_ln36_1_fu_423_p2;
wire  signed [32:0] sext_ln36_fu_445_p1;
wire  signed [32:0] row_start_cast_fu_442_p1;
wire   [0:0] icmp_ln36_fu_438_p2;
wire   [32:0] sub_ln36_fu_448_p2;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
reg    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
reg    ap_ST_fsm_state39_blk;
wire   [63:0] gmem4_0_AWLEN0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 39'd1;
#0 grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start_reg = 1'b0;
#0 grp_spmv_csr_Pipeline_L2_fu_234_ap_start_reg = 1'b0;
#0 i_1_fu_126 = 31'd0;
end

spmv_csr_x_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
x_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_buf_address0),
    .ce0(x_buf_ce0),
    .we0(x_buf_we0),
    .d0(grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_d0),
    .q0(x_buf_q0)
);

spmv_csr_spmv_csr_Pipeline_READ_X grp_spmv_csr_Pipeline_READ_X_fu_225(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start),
    .ap_done(grp_spmv_csr_Pipeline_READ_X_fu_225_ap_done),
    .ap_idle(grp_spmv_csr_Pipeline_READ_X_fu_225_ap_idle),
    .ap_ready(grp_spmv_csr_Pipeline_READ_X_fu_225_ap_ready),
    .m_axi_gmem3_0_AWVALID(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWVALID),
    .m_axi_gmem3_0_AWREADY(1'b0),
    .m_axi_gmem3_0_AWADDR(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWADDR),
    .m_axi_gmem3_0_AWID(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWID),
    .m_axi_gmem3_0_AWLEN(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWLEN),
    .m_axi_gmem3_0_AWSIZE(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWSIZE),
    .m_axi_gmem3_0_AWBURST(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWBURST),
    .m_axi_gmem3_0_AWLOCK(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWLOCK),
    .m_axi_gmem3_0_AWCACHE(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWCACHE),
    .m_axi_gmem3_0_AWPROT(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWPROT),
    .m_axi_gmem3_0_AWQOS(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWQOS),
    .m_axi_gmem3_0_AWREGION(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWREGION),
    .m_axi_gmem3_0_AWUSER(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_AWUSER),
    .m_axi_gmem3_0_WVALID(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WVALID),
    .m_axi_gmem3_0_WREADY(1'b0),
    .m_axi_gmem3_0_WDATA(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WDATA),
    .m_axi_gmem3_0_WSTRB(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WSTRB),
    .m_axi_gmem3_0_WLAST(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WLAST),
    .m_axi_gmem3_0_WID(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WID),
    .m_axi_gmem3_0_WUSER(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_WUSER),
    .m_axi_gmem3_0_ARVALID(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARVALID),
    .m_axi_gmem3_0_ARREADY(gmem3_0_ARREADY),
    .m_axi_gmem3_0_ARADDR(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARADDR),
    .m_axi_gmem3_0_ARID(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARID),
    .m_axi_gmem3_0_ARLEN(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARLEN),
    .m_axi_gmem3_0_ARSIZE(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARSIZE),
    .m_axi_gmem3_0_ARBURST(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARBURST),
    .m_axi_gmem3_0_ARLOCK(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARLOCK),
    .m_axi_gmem3_0_ARCACHE(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARCACHE),
    .m_axi_gmem3_0_ARPROT(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARPROT),
    .m_axi_gmem3_0_ARQOS(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARQOS),
    .m_axi_gmem3_0_ARREGION(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARREGION),
    .m_axi_gmem3_0_ARUSER(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARUSER),
    .m_axi_gmem3_0_RVALID(gmem3_0_RVALID),
    .m_axi_gmem3_0_RREADY(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_RREADY),
    .m_axi_gmem3_0_RDATA(gmem3_0_RDATA),
    .m_axi_gmem3_0_RLAST(1'b0),
    .m_axi_gmem3_0_RID(1'd0),
    .m_axi_gmem3_0_RFIFONUM(gmem3_0_RFIFONUM),
    .m_axi_gmem3_0_RUSER(1'd0),
    .m_axi_gmem3_0_RRESP(2'd0),
    .m_axi_gmem3_0_BVALID(1'b0),
    .m_axi_gmem3_0_BREADY(grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_BREADY),
    .m_axi_gmem3_0_BRESP(2'd0),
    .m_axi_gmem3_0_BID(1'd0),
    .m_axi_gmem3_0_BUSER(1'd0),
    .num_cols(num_cols_read_reg_517),
    .sext_ln23(trunc_ln_reg_533),
    .x_buf_address0(grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_address0),
    .x_buf_ce0(grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_ce0),
    .x_buf_we0(grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_we0),
    .x_buf_d0(grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_d0)
);

spmv_csr_spmv_csr_Pipeline_L2 grp_spmv_csr_Pipeline_L2_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_spmv_csr_Pipeline_L2_fu_234_ap_start),
    .ap_done(grp_spmv_csr_Pipeline_L2_fu_234_ap_done),
    .ap_idle(grp_spmv_csr_Pipeline_L2_fu_234_ap_idle),
    .ap_ready(grp_spmv_csr_Pipeline_L2_fu_234_ap_ready),
    .m_axi_gmem2_0_AWVALID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(1'b0),
    .m_axi_gmem2_0_RID(1'd0),
    .m_axi_gmem2_0_RFIFONUM(gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(1'd0),
    .m_axi_gmem2_0_RRESP(2'd0),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .m_axi_gmem1_0_AWVALID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .sext_ln36(row_start_reg_574),
    .wide_trip_count(row_end_reg_582),
    .sext_ln36_1(trunc_ln3_reg_589),
    .sext_ln36_2(trunc_ln36_1_reg_595),
    .x_buf_address0(grp_spmv_csr_Pipeline_L2_fu_234_x_buf_address0),
    .x_buf_ce0(grp_spmv_csr_Pipeline_L2_fu_234_x_buf_ce0),
    .x_buf_q0(x_buf_q0),
    .sum_out(grp_spmv_csr_Pipeline_L2_fu_234_sum_out),
    .sum_out_ap_vld(grp_spmv_csr_Pipeline_L2_fu_234_sum_out_ap_vld)
);

spmv_csr_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_rows(num_rows),
    .num_cols(num_cols),
    .A_row_index(A_row_index),
    .A_col_index(A_col_index),
    .A_values(A_values),
    .x(x),
    .y(y),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

spmv_csr_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(gmem0_addr_reg_568),
    .I_CH0_ARLEN(gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

spmv_csr_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem1_0_ARVALID),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(gmem1_0_ARADDR),
    .I_CH0_ARLEN(gmem1_0_ARLEN),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(gmem1_0_RREADY),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

spmv_csr_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem2_0_ARVALID),
    .I_CH0_ARREADY(gmem2_0_ARREADY),
    .I_CH0_ARADDR(gmem2_0_ARADDR),
    .I_CH0_ARLEN(gmem2_0_ARLEN),
    .I_CH0_RVALID(gmem2_0_RVALID),
    .I_CH0_RREADY(gmem2_0_RREADY),
    .I_CH0_RDATA(gmem2_0_RDATA),
    .I_CH0_RFIFONUM(gmem2_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem2_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem2_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem2_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

spmv_csr_gmem3_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM3_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM3_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem3_m_axi_U(
    .AWVALID(m_axi_gmem3_AWVALID),
    .AWREADY(m_axi_gmem3_AWREADY),
    .AWADDR(m_axi_gmem3_AWADDR),
    .AWID(m_axi_gmem3_AWID),
    .AWLEN(m_axi_gmem3_AWLEN),
    .AWSIZE(m_axi_gmem3_AWSIZE),
    .AWBURST(m_axi_gmem3_AWBURST),
    .AWLOCK(m_axi_gmem3_AWLOCK),
    .AWCACHE(m_axi_gmem3_AWCACHE),
    .AWPROT(m_axi_gmem3_AWPROT),
    .AWQOS(m_axi_gmem3_AWQOS),
    .AWREGION(m_axi_gmem3_AWREGION),
    .AWUSER(m_axi_gmem3_AWUSER),
    .WVALID(m_axi_gmem3_WVALID),
    .WREADY(m_axi_gmem3_WREADY),
    .WDATA(m_axi_gmem3_WDATA),
    .WSTRB(m_axi_gmem3_WSTRB),
    .WLAST(m_axi_gmem3_WLAST),
    .WID(m_axi_gmem3_WID),
    .WUSER(m_axi_gmem3_WUSER),
    .ARVALID(m_axi_gmem3_ARVALID),
    .ARREADY(m_axi_gmem3_ARREADY),
    .ARADDR(m_axi_gmem3_ARADDR),
    .ARID(m_axi_gmem3_ARID),
    .ARLEN(m_axi_gmem3_ARLEN),
    .ARSIZE(m_axi_gmem3_ARSIZE),
    .ARBURST(m_axi_gmem3_ARBURST),
    .ARLOCK(m_axi_gmem3_ARLOCK),
    .ARCACHE(m_axi_gmem3_ARCACHE),
    .ARPROT(m_axi_gmem3_ARPROT),
    .ARQOS(m_axi_gmem3_ARQOS),
    .ARREGION(m_axi_gmem3_ARREGION),
    .ARUSER(m_axi_gmem3_ARUSER),
    .RVALID(m_axi_gmem3_RVALID),
    .RREADY(m_axi_gmem3_RREADY),
    .RDATA(m_axi_gmem3_RDATA),
    .RLAST(m_axi_gmem3_RLAST),
    .RID(m_axi_gmem3_RID),
    .RUSER(m_axi_gmem3_RUSER),
    .RRESP(m_axi_gmem3_RRESP),
    .BVALID(m_axi_gmem3_BVALID),
    .BREADY(m_axi_gmem3_BREADY),
    .BRESP(m_axi_gmem3_BRESP),
    .BID(m_axi_gmem3_BID),
    .BUSER(m_axi_gmem3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem3_0_ARVALID),
    .I_CH0_ARREADY(gmem3_0_ARREADY),
    .I_CH0_ARADDR(gmem3_0_ARADDR),
    .I_CH0_ARLEN(gmem3_0_ARLEN),
    .I_CH0_RVALID(gmem3_0_RVALID),
    .I_CH0_RREADY(gmem3_0_RREADY),
    .I_CH0_RDATA(gmem3_0_RDATA),
    .I_CH0_RFIFONUM(gmem3_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem3_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem3_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem3_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

spmv_csr_gmem4_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM4_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM4_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM4_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM4_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM4_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM4_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM4_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM4_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM4_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM4_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM4_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem4_m_axi_U(
    .AWVALID(m_axi_gmem4_AWVALID),
    .AWREADY(m_axi_gmem4_AWREADY),
    .AWADDR(m_axi_gmem4_AWADDR),
    .AWID(m_axi_gmem4_AWID),
    .AWLEN(m_axi_gmem4_AWLEN),
    .AWSIZE(m_axi_gmem4_AWSIZE),
    .AWBURST(m_axi_gmem4_AWBURST),
    .AWLOCK(m_axi_gmem4_AWLOCK),
    .AWCACHE(m_axi_gmem4_AWCACHE),
    .AWPROT(m_axi_gmem4_AWPROT),
    .AWQOS(m_axi_gmem4_AWQOS),
    .AWREGION(m_axi_gmem4_AWREGION),
    .AWUSER(m_axi_gmem4_AWUSER),
    .WVALID(m_axi_gmem4_WVALID),
    .WREADY(m_axi_gmem4_WREADY),
    .WDATA(m_axi_gmem4_WDATA),
    .WSTRB(m_axi_gmem4_WSTRB),
    .WLAST(m_axi_gmem4_WLAST),
    .WID(m_axi_gmem4_WID),
    .WUSER(m_axi_gmem4_WUSER),
    .ARVALID(m_axi_gmem4_ARVALID),
    .ARREADY(m_axi_gmem4_ARREADY),
    .ARADDR(m_axi_gmem4_ARADDR),
    .ARID(m_axi_gmem4_ARID),
    .ARLEN(m_axi_gmem4_ARLEN),
    .ARSIZE(m_axi_gmem4_ARSIZE),
    .ARBURST(m_axi_gmem4_ARBURST),
    .ARLOCK(m_axi_gmem4_ARLOCK),
    .ARCACHE(m_axi_gmem4_ARCACHE),
    .ARPROT(m_axi_gmem4_ARPROT),
    .ARQOS(m_axi_gmem4_ARQOS),
    .ARREGION(m_axi_gmem4_ARREGION),
    .ARUSER(m_axi_gmem4_ARUSER),
    .RVALID(m_axi_gmem4_RVALID),
    .RREADY(m_axi_gmem4_RREADY),
    .RDATA(m_axi_gmem4_RDATA),
    .RLAST(m_axi_gmem4_RLAST),
    .RID(m_axi_gmem4_RID),
    .RUSER(m_axi_gmem4_RUSER),
    .RRESP(m_axi_gmem4_RRESP),
    .BVALID(m_axi_gmem4_BVALID),
    .BREADY(m_axi_gmem4_BREADY),
    .BRESP(m_axi_gmem4_BRESP),
    .BID(m_axi_gmem4_BID),
    .BUSER(m_axi_gmem4_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem4_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem4_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem4_0_RDATA),
    .I_CH0_RFIFONUM(gmem4_0_RFIFONUM),
    .I_CH0_AWVALID(gmem4_0_AWVALID),
    .I_CH0_AWREADY(gmem4_0_AWREADY),
    .I_CH0_AWADDR(gmem4_addr_reg_544),
    .I_CH0_AWLEN(gmem4_0_AWLEN),
    .I_CH0_WVALID(gmem4_0_WVALID),
    .I_CH0_WREADY(gmem4_0_WREADY),
    .I_CH0_WDATA(gmem4_0_WDATA),
    .I_CH0_WSTRB(4'd15),
    .I_CH0_BVALID(gmem4_0_BVALID),
    .I_CH0_BREADY(gmem4_0_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_spmv_csr_Pipeline_L2_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state32) & (1'b1 == ap_CS_fsm_state31))) begin
            grp_spmv_csr_Pipeline_L2_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_spmv_csr_Pipeline_L2_fu_234_ap_ready == 1'b1)) begin
            grp_spmv_csr_Pipeline_L2_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start_reg <= 1'b1;
        end else if ((grp_spmv_csr_Pipeline_READ_X_fu_225_ap_ready == 1'b1)) begin
            grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_1_fu_126 <= 31'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln29_1_fu_344_p2 == 1'd1))) begin
        i_1_fu_126 <= add_ln33_fu_349_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        A_col_index_read_reg_507 <= A_col_index;
        A_row_index_read_reg_512 <= A_row_index;
        A_values_read_reg_502 <= A_values;
        empty_29_reg_550 <= empty_29_fu_306_p3;
        empty_reg_539 <= empty_fu_268_p3;
        gmem4_addr_reg_544 <= sext_ln29_fu_296_p1;
        num_cols_read_reg_517 <= num_cols;
        num_rows_read_reg_522 <= num_rows;
        trunc_ln_reg_533 <= {{x[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        empty_32_reg_601 <= empty_32_fu_454_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gmem0_addr_reg_568 <= sext_ln32_fu_382_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        row_end_reg_582 <= gmem0_0_RDATA;
        trunc_ln36_1_reg_595 <= {{add_ln36_1_fu_423_p2[63:2]}};
        trunc_ln3_reg_589 <= {{add_ln36_fu_408_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        row_start_reg_574 <= gmem0_0_RDATA;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_spmv_csr_Pipeline_READ_X_fu_225_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((gmem0_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((gmem0_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem0_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state24_io)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

always @ (*) begin
    if ((grp_spmv_csr_Pipeline_L2_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state33_blk = 1'b1;
    end else begin
        ap_ST_fsm_state33_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem4_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

always @ (*) begin
    if ((gmem4_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state39_blk = 1'b1;
    end else begin
        ap_ST_fsm_state39_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem4_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem4_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        gmem0_0_ARVALID = 1'b1;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem0_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((gmem0_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state21)))) begin
        gmem0_0_RREADY = 1'b1;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24_io))) begin
        gmem1_0_ARADDR = sext_ln36_2_fu_477_p1;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem1_0_ARADDR = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARADDR;
    end else begin
        gmem1_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24_io))) begin
        gmem1_0_ARLEN = sext_ln36_4_fu_472_p1;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem1_0_ARLEN = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARLEN;
    end else begin
        gmem1_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24_io))) begin
        gmem1_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem1_0_ARVALID = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_ARVALID;
    end else begin
        gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem1_0_RREADY = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem1_0_RREADY;
    end else begin
        gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24_io))) begin
        gmem2_0_ARADDR = sext_ln36_1_fu_462_p1;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem2_0_ARADDR = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARADDR;
    end else begin
        gmem2_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24_io))) begin
        gmem2_0_ARLEN = sext_ln36_4_fu_472_p1;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem2_0_ARLEN = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARLEN;
    end else begin
        gmem2_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24_io))) begin
        gmem2_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem2_0_ARVALID = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_ARVALID;
    end else begin
        gmem2_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        gmem2_0_RREADY = grp_spmv_csr_Pipeline_L2_fu_234_m_axi_gmem2_0_RREADY;
    end else begin
        gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        gmem2_blk_n_AR = m_axi_gmem2_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        gmem3_0_ARADDR = sext_ln23_fu_319_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem3_0_ARADDR = grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARADDR;
    end else begin
        gmem3_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        gmem3_0_ARLEN = zext_ln23_fu_329_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem3_0_ARLEN = grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARLEN;
    end else begin
        gmem3_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        gmem3_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem3_0_ARVALID = grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_ARVALID;
    end else begin
        gmem3_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem3_0_RREADY = grp_spmv_csr_Pipeline_READ_X_fu_225_m_axi_gmem3_0_RREADY;
    end else begin
        gmem3_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem3_blk_n_AR = m_axi_gmem3_ARREADY;
    end else begin
        gmem3_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        gmem4_0_AWVALID = 1'b1;
    end else begin
        gmem4_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem4_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
        gmem4_0_BREADY = 1'b1;
    end else begin
        gmem4_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem4_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
        gmem4_0_WVALID = 1'b1;
    end else begin
        gmem4_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem4_blk_n_AW = m_axi_gmem4_AWREADY;
    end else begin
        gmem4_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        gmem4_blk_n_B = m_axi_gmem4_BVALID;
    end else begin
        gmem4_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        gmem4_blk_n_W = m_axi_gmem4_WREADY;
    end else begin
        gmem4_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        x_buf_address0 = grp_spmv_csr_Pipeline_L2_fu_234_x_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_buf_address0 = grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_address0;
    end else begin
        x_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        x_buf_ce0 = grp_spmv_csr_Pipeline_L2_fu_234_x_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_buf_ce0 = grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_ce0;
    end else begin
        x_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        x_buf_we0 = grp_spmv_csr_Pipeline_READ_X_fu_225_x_buf_we0;
    end else begin
        x_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_spmv_csr_Pipeline_READ_X_fu_225_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln29_1_fu_344_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((gmem0_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((gmem0_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24_io))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            if (((grp_spmv_csr_Pipeline_L2_fu_234_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state34 : begin
            if (((gmem4_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            if (((gmem4_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_367_p2 = (zext_ln32_fu_363_p1 + A_row_index_read_reg_512);

assign add_ln33_fu_349_p2 = (i_1_fu_126 + 31'd1);

assign add_ln36_1_fu_423_p2 = ($signed(sext_ln36_3_fu_404_p1) + $signed(A_col_index_read_reg_507));

assign add_ln36_fu_408_p2 = ($signed(sext_ln36_3_fu_404_p1) + $signed(A_values_read_reg_502));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_NS_fsm_state32 = ap_NS_fsm[32'd31];

always @ (*) begin
    ap_block_state24_io = ((gmem2_0_ARREADY == 1'b0) | (gmem1_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((gmem4_0_AWREADY == 1'b0) | (gmem3_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_29_fu_306_p3 = ((icmp_ln29_fu_276_p2[0:0] == 1'b1) ? trunc_ln29_fu_282_p1 : 31'd0);

assign empty_32_fu_454_p3 = ((icmp_ln36_fu_438_p2[0:0] == 1'b1) ? sub_ln36_fu_448_p2 : 33'd0);

assign empty_fu_268_p3 = ((icmp_ln23_fu_248_p2[0:0] == 1'b1) ? trunc_ln23_fu_254_p1 : 31'd0);

assign gmem0_0_ARLEN = 64'd2;

assign gmem4_0_AWLEN = gmem4_0_AWLEN0;

assign gmem4_0_AWLEN0 = empty_29_reg_550;

assign gmem4_0_WDATA = grp_spmv_csr_Pipeline_L2_fu_234_sum_out;

assign grp_spmv_csr_Pipeline_L2_fu_234_ap_start = grp_spmv_csr_Pipeline_L2_fu_234_ap_start_reg;

assign grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start = grp_spmv_csr_Pipeline_READ_X_fu_225_ap_start_reg;

assign icmp_ln23_fu_248_p2 = (($signed(num_cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln29_1_fu_344_p2 = (($signed(zext_ln29_1_fu_340_p1) < $signed(num_rows_read_reg_522)) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_276_p2 = (($signed(num_rows) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_438_p2 = (($signed(row_start_reg_574) < $signed(row_end_reg_582)) ? 1'b1 : 1'b0);

assign row_start_cast_fu_442_p1 = $signed(row_start_reg_574);

assign sext_ln23_fu_319_p1 = $signed(trunc_ln_reg_533);

assign sext_ln29_fu_296_p1 = $signed(trunc_ln1_fu_286_p4);

assign sext_ln32_fu_382_p1 = $signed(trunc_ln2_fu_372_p4);

assign sext_ln36_1_fu_462_p1 = $signed(trunc_ln3_reg_589);

assign sext_ln36_2_fu_477_p1 = $signed(trunc_ln36_1_reg_595);

assign sext_ln36_3_fu_404_p1 = $signed(shl_ln1_fu_397_p3);

assign sext_ln36_4_fu_472_p1 = $signed(empty_32_reg_601);

assign sext_ln36_fu_445_p1 = $signed(row_end_reg_582);

assign shl_ln1_fu_397_p3 = {{row_start_reg_574}, {2'd0}};

assign shl_ln_fu_355_p3 = {{i_1_fu_126}, {2'd0}};

assign sub_ln36_fu_448_p2 = ($signed(sext_ln36_fu_445_p1) - $signed(row_start_cast_fu_442_p1));

assign trunc_ln1_fu_286_p4 = {{y[63:2]}};

assign trunc_ln23_fu_254_p1 = num_cols[30:0];

assign trunc_ln29_fu_282_p1 = num_rows[30:0];

assign trunc_ln2_fu_372_p4 = {{add_ln32_fu_367_p2[63:2]}};

assign zext_ln23_fu_329_p1 = empty_reg_539;

assign zext_ln29_1_fu_340_p1 = i_1_fu_126;

assign zext_ln32_fu_363_p1 = shl_ln_fu_355_p3;

endmodule //spmv_csr
