-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spmv_csc_compute_pe_13 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    num_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    num_rows_empty_n : IN STD_LOGIC;
    num_rows_read : OUT STD_LOGIC;
    num_rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    pe_streams_13_dout : IN STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_13_empty_n : IN STD_LOGIC;
    pe_streams_13_read : OUT STD_LOGIC;
    pe_streams_13_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    pe_streams_13_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    y_partial_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    y_partial_ce0 : OUT STD_LOGIC;
    y_partial_we0 : OUT STD_LOGIC;
    y_partial_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_partial_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of spmv_csc_compute_pe_13 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal num_rows_blk_n : STD_LOGIC;
    signal num_rows_11_reg_84 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_done : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_idle : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_ready : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_ce0 : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_we0 : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_idle : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_ready : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_pe_streams_13_read : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_ce0 : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_we0 : STD_LOGIC;
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component spmv_csc_compute_pe_13_Pipeline_VITIS_LOOP_245_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        num_rows_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        y_partial_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        y_partial_ce0 : OUT STD_LOGIC;
        y_partial_we0 : OUT STD_LOGIC;
        y_partial_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component spmv_csc_compute_pe_13_Pipeline_VITIS_LOOP_251_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pe_streams_13_dout : IN STD_LOGIC_VECTOR (96 downto 0);
        pe_streams_13_empty_n : IN STD_LOGIC;
        pe_streams_13_read : OUT STD_LOGIC;
        pe_streams_13_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        pe_streams_13_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        num_rows_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        y_partial_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        y_partial_ce0 : OUT STD_LOGIC;
        y_partial_we0 : OUT STD_LOGIC;
        y_partial_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        y_partial_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48 : component spmv_csc_compute_pe_13_Pipeline_VITIS_LOOP_245_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start,
        ap_done => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_done,
        ap_idle => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_idle,
        ap_ready => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_ready,
        num_rows_11 => num_rows_11_reg_84,
        y_partial_address0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_address0,
        y_partial_ce0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_ce0,
        y_partial_we0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_we0,
        y_partial_d0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_d0);

    grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55 : component spmv_csc_compute_pe_13_Pipeline_VITIS_LOOP_251_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start,
        ap_done => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done,
        ap_idle => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_idle,
        ap_ready => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_ready,
        pe_streams_13_dout => pe_streams_13_dout,
        pe_streams_13_empty_n => pe_streams_13_empty_n,
        pe_streams_13_read => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_pe_streams_13_read,
        pe_streams_13_num_data_valid => ap_const_lv9_0,
        pe_streams_13_fifo_cap => ap_const_lv9_0,
        num_rows_11 => num_rows_11_reg_84,
        y_partial_address0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_address0,
        y_partial_ce0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_ce0,
        y_partial_we0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_we0,
        y_partial_d0 => grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_d0,
        y_partial_q0 => y_partial_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_ready = ap_const_logic_1)) then 
                    grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_ready = ap_const_logic_1)) then 
                    grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                num_rows_11_reg_84 <= num_rows_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_done, grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_done)
    begin
        if ((grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done)
    begin
        if ((grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, num_rows_empty_n)
    begin
                ap_block_state1 <= ((num_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start <= grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_ap_start_reg;
    grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start <= grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_ap_start_reg;

    num_rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_blk_n <= num_rows_empty_n;
        else 
            num_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    num_rows_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_read <= ap_const_logic_1;
        else 
            num_rows_read <= ap_const_logic_0;
        end if; 
    end process;

    pe_streams_13_read <= grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_pe_streams_13_read;

    y_partial_address0_assign_proc : process(grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_address0, grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y_partial_address0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_partial_address0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_address0;
        else 
            y_partial_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    y_partial_ce0_assign_proc : process(grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_ce0, grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y_partial_ce0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_partial_ce0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_ce0;
        else 
            y_partial_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y_partial_d0_assign_proc : process(grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_d0, grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_d0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y_partial_d0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_partial_d0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_d0;
        else 
            y_partial_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    y_partial_we0_assign_proc : process(grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_we0, grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_we0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y_partial_we0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_251_2_fu_55_y_partial_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_partial_we0 <= grp_compute_pe_13_Pipeline_VITIS_LOOP_245_1_fu_48_y_partial_we0;
        else 
            y_partial_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
