-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spmv_csc_distribute_to_pe_Pipeline_VITIS_LOOP_230_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pe_streams_14_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_14_full_n : IN STD_LOGIC;
    pe_streams_14_write : OUT STD_LOGIC;
    pe_streams_14_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_14_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_13_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_13_full_n : IN STD_LOGIC;
    pe_streams_13_write : OUT STD_LOGIC;
    pe_streams_13_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_13_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_12_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_12_full_n : IN STD_LOGIC;
    pe_streams_12_write : OUT STD_LOGIC;
    pe_streams_12_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_12_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_11_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_11_full_n : IN STD_LOGIC;
    pe_streams_11_write : OUT STD_LOGIC;
    pe_streams_11_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_11_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_10_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_10_full_n : IN STD_LOGIC;
    pe_streams_10_write : OUT STD_LOGIC;
    pe_streams_10_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_10_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_9_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_9_full_n : IN STD_LOGIC;
    pe_streams_9_write : OUT STD_LOGIC;
    pe_streams_9_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_9_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_8_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_8_full_n : IN STD_LOGIC;
    pe_streams_8_write : OUT STD_LOGIC;
    pe_streams_8_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_8_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_7_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_7_full_n : IN STD_LOGIC;
    pe_streams_7_write : OUT STD_LOGIC;
    pe_streams_7_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_7_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_6_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_6_full_n : IN STD_LOGIC;
    pe_streams_6_write : OUT STD_LOGIC;
    pe_streams_6_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_6_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_5_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_5_full_n : IN STD_LOGIC;
    pe_streams_5_write : OUT STD_LOGIC;
    pe_streams_5_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_5_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_4_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_4_full_n : IN STD_LOGIC;
    pe_streams_4_write : OUT STD_LOGIC;
    pe_streams_4_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_4_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_3_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_3_full_n : IN STD_LOGIC;
    pe_streams_3_write : OUT STD_LOGIC;
    pe_streams_3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_2_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_2_full_n : IN STD_LOGIC;
    pe_streams_2_write : OUT STD_LOGIC;
    pe_streams_2_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_2_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_1_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_1_full_n : IN STD_LOGIC;
    pe_streams_1_write : OUT STD_LOGIC;
    pe_streams_1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_0_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_0_full_n : IN STD_LOGIC;
    pe_streams_0_write : OUT STD_LOGIC;
    pe_streams_0_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_0_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_15_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    pe_streams_15_full_n : IN STD_LOGIC;
    pe_streams_15_write : OUT STD_LOGIC;
    pe_streams_15_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    pe_streams_15_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of spmv_csc_distribute_to_pe_Pipeline_VITIS_LOOP_230_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv97_1000000000000000000000000 : STD_LOGIC_VECTOR (96 downto 0) := "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal trunc_ln230_reg_265 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp3 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp4 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp5 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp6_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp6 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp7_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp7 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp8_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp8 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp9_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp9 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp10 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp10_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp10 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp11 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp11_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp11 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp12 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp12_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp12 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp13 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp13_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp13 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp14 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp14_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp14 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp15 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp15_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp15 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp16 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp16_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp16 : BOOLEAN;
    signal icmp_ln230_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal pe_streams_0_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp15 : BOOLEAN;
    signal pe_streams_1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp14 : BOOLEAN;
    signal pe_streams_2_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp13 : BOOLEAN;
    signal pe_streams_3_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp12 : BOOLEAN;
    signal pe_streams_4_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp11 : BOOLEAN;
    signal pe_streams_5_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp10 : BOOLEAN;
    signal pe_streams_6_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp9 : BOOLEAN;
    signal pe_streams_7_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp8 : BOOLEAN;
    signal pe_streams_8_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp7 : BOOLEAN;
    signal pe_streams_9_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp6 : BOOLEAN;
    signal pe_streams_10_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp5 : BOOLEAN;
    signal pe_streams_11_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp4 : BOOLEAN;
    signal pe_streams_12_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp3 : BOOLEAN;
    signal pe_streams_13_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal pe_streams_14_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal pe_streams_15_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp16 : BOOLEAN;
    signal trunc_ln230_fu_246_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_94 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln230_fu_240_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp9 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp10 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp10 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp11 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp11 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp12 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp12 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp13 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp13 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp14 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp14 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp15 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp15 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp16 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp16 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component spmv_csc_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component spmv_csc_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp10_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp10_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp10_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10)) then 
                    ap_block_pp0_stage0_subdone_grp10_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp11_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp11_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp11_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11)) then 
                    ap_block_pp0_stage0_subdone_grp11_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp12_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp12_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp12_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12)) then 
                    ap_block_pp0_stage0_subdone_grp12_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp13_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp13_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp13_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13)) then 
                    ap_block_pp0_stage0_subdone_grp13_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp14_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp14_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp14_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14)) then 
                    ap_block_pp0_stage0_subdone_grp14_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp15_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp15_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp15_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15)) then 
                    ap_block_pp0_stage0_subdone_grp15_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp16_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp16_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp16_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16)) then 
                    ap_block_pp0_stage0_subdone_grp16_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                    ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp4_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4)) then 
                    ap_block_pp0_stage0_subdone_grp4_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5)) then 
                    ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp6_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6)) then 
                    ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp7_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7)) then 
                    ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp8_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8)) then 
                    ap_block_pp0_stage0_subdone_grp8_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp9_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9)) then 
                    ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln230_fu_234_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_94 <= add_ln230_fu_240_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_94 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln230_reg_265 <= trunc_ln230_fu_246_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln230_fu_240_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp10_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp10, ap_block_pp0_stage0_subdone_grp10_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp10 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp11_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp11, ap_block_pp0_stage0_subdone_grp11_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp11 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp11) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp12_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp12, ap_block_pp0_stage0_subdone_grp12_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp12 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp12) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp13_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp13, ap_block_pp0_stage0_subdone_grp13_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp13 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp13) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp14_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp14, ap_block_pp0_stage0_subdone_grp14_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp14 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp14) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp15_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp15, ap_block_pp0_stage0_subdone_grp15_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp15 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp15) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp16_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp16, ap_block_pp0_stage0_subdone_grp16_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp16 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp16) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp2, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp3 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp4, ap_block_pp0_stage0_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp4 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp5 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp6 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp7 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp8, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp8 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg));
    end process;


    ap_block_pp0_stage0_01001_grp9_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp9, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp9 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state2_pp0_stage0_iter1_grp2, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state2_pp0_stage0_iter1_grp4, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state2_pp0_stage0_iter1_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_state2_pp0_stage0_iter1_grp8, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_block_state2_pp0_stage0_iter1_grp9, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_state2_pp0_stage0_iter1_grp10, ap_block_pp0_stage0_subdone_grp10_done_reg, ap_block_state2_pp0_stage0_iter1_grp11, ap_block_pp0_stage0_subdone_grp11_done_reg, ap_block_state2_pp0_stage0_iter1_grp12, ap_block_pp0_stage0_subdone_grp12_done_reg, ap_block_state2_pp0_stage0_iter1_grp13, ap_block_pp0_stage0_subdone_grp13_done_reg, ap_block_state2_pp0_stage0_iter1_grp14, ap_block_pp0_stage0_subdone_grp14_done_reg, ap_block_state2_pp0_stage0_iter1_grp15, ap_block_pp0_stage0_subdone_grp15_done_reg, ap_block_state2_pp0_stage0_iter1_grp16, ap_block_pp0_stage0_subdone_grp16_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp16) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp15) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp14) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp13) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp12) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp11) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10_done_reg)) or ((ap_const_boolean_1 
    = ap_block_state2_pp0_stage0_iter1_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) 
    or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp10_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp10, ap_block_pp0_stage0_subdone_grp10_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp10 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp11_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp11, ap_block_pp0_stage0_subdone_grp11_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp11 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp11) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp12_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp12, ap_block_pp0_stage0_subdone_grp12_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp12 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp12) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp13_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp13, ap_block_pp0_stage0_subdone_grp13_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp13 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp13) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp14_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp14, ap_block_pp0_stage0_subdone_grp14_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp14 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp14) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp15_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp15, ap_block_pp0_stage0_subdone_grp15_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp15 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp15) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp16_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp16, ap_block_pp0_stage0_subdone_grp16_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp16 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp16) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp2, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp3 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp4, ap_block_pp0_stage0_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp4 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp5 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp6 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp7 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp8, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp8 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp9, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp9 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state2_pp0_stage0_iter1_grp2, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state2_pp0_stage0_iter1_grp4, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state2_pp0_stage0_iter1_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_state2_pp0_stage0_iter1_grp8, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_block_state2_pp0_stage0_iter1_grp9, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_state2_pp0_stage0_iter1_grp10, ap_block_pp0_stage0_subdone_grp10_done_reg, ap_block_state2_pp0_stage0_iter1_grp11, ap_block_pp0_stage0_subdone_grp11_done_reg, ap_block_state2_pp0_stage0_iter1_grp12, ap_block_pp0_stage0_subdone_grp12_done_reg, ap_block_state2_pp0_stage0_iter1_grp13, ap_block_pp0_stage0_subdone_grp13_done_reg, ap_block_state2_pp0_stage0_iter1_grp14, ap_block_pp0_stage0_subdone_grp14_done_reg, ap_block_state2_pp0_stage0_iter1_grp15, ap_block_pp0_stage0_subdone_grp15_done_reg, ap_block_state2_pp0_stage0_iter1_grp16, ap_block_pp0_stage0_subdone_grp16_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp16) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp15) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp14) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp13) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp12) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp11) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10_done_reg)) or ((ap_const_boolean_1 
    = ap_block_state2_pp0_stage0_iter1_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) 
    or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp10_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp10, ap_block_pp0_stage0_subdone_grp10_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp10 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp11_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp11, ap_block_pp0_stage0_subdone_grp11_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp11 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp11) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp12_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp12, ap_block_pp0_stage0_subdone_grp12_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp12 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp12) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp13_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp13, ap_block_pp0_stage0_subdone_grp13_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp13 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp13) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp14_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp14, ap_block_pp0_stage0_subdone_grp14_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp14 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp14) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp15_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp15, ap_block_pp0_stage0_subdone_grp15_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp15 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp15) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp16_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp16, ap_block_pp0_stage0_subdone_grp16_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp16 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp16) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp2, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp3 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp4, ap_block_pp0_stage0_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp4 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp5 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp6 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp7 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp8, ap_block_pp0_stage0_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp8 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp9_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp9, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp9 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(pe_streams_14_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= ((pe_streams_14_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_E));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp10_assign_proc : process(pe_streams_5_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp10 <= ((pe_streams_5_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_5));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp11_assign_proc : process(pe_streams_4_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp11 <= ((pe_streams_4_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_4));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp12_assign_proc : process(pe_streams_3_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp12 <= ((pe_streams_3_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_3));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp13_assign_proc : process(pe_streams_2_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp13 <= ((trunc_ln230_reg_265 = ap_const_lv4_2) and (pe_streams_2_full_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp14_assign_proc : process(pe_streams_1_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp14 <= ((trunc_ln230_reg_265 = ap_const_lv4_1) and (pe_streams_1_full_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp15_assign_proc : process(pe_streams_0_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp15 <= ((trunc_ln230_reg_265 = ap_const_lv4_0) and (pe_streams_0_full_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp16_assign_proc : process(pe_streams_15_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp16 <= ((trunc_ln230_reg_265 = ap_const_lv4_F) and (pe_streams_15_full_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp2_assign_proc : process(pe_streams_13_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp2 <= ((pe_streams_13_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_D));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp3_assign_proc : process(pe_streams_12_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp3 <= ((pe_streams_12_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_C));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp4_assign_proc : process(pe_streams_11_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp4 <= ((pe_streams_11_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_B));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp5_assign_proc : process(pe_streams_10_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp5 <= ((pe_streams_10_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_A));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp6_assign_proc : process(pe_streams_9_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp6 <= ((pe_streams_9_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_9));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp7_assign_proc : process(pe_streams_8_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp7 <= ((pe_streams_8_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_8));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp8_assign_proc : process(pe_streams_7_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp8 <= ((pe_streams_7_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_7));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp9_assign_proc : process(pe_streams_6_full_n, trunc_ln230_reg_265)
    begin
                ap_block_state2_pp0_stage0_iter1_grp9 <= ((pe_streams_6_full_n = ap_const_logic_0) and (trunc_ln230_reg_265 = ap_const_lv4_6));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln230_fu_234_p2)
    begin
        if (((icmp_ln230_fu_234_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_94, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_94;
        end if; 
    end process;

    icmp_ln230_fu_234_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv5_10) else "0";

    pe_streams_0_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_0_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp15_done_reg, ap_block_pp0_stage0_grp15)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp15) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_0))) then 
            pe_streams_0_blk_n <= pe_streams_0_full_n;
        else 
            pe_streams_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_0_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_0_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp15_done_reg, ap_block_pp0_stage0_11001_grp15)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp15) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp15_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_0))) then 
            pe_streams_0_write <= ap_const_logic_1;
        else 
            pe_streams_0_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_10_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_10_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_grp5)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_A))) then 
            pe_streams_10_blk_n <= pe_streams_10_full_n;
        else 
            pe_streams_10_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_10_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_10_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_11001_grp5)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_A))) then 
            pe_streams_10_write <= ap_const_logic_1;
        else 
            pe_streams_10_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_11_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_11_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_pp0_stage0_grp4)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_B))) then 
            pe_streams_11_blk_n <= pe_streams_11_full_n;
        else 
            pe_streams_11_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_11_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_11_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_pp0_stage0_11001_grp4)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_B))) then 
            pe_streams_11_write <= ap_const_logic_1;
        else 
            pe_streams_11_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_12_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_12_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_grp3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_C))) then 
            pe_streams_12_blk_n <= pe_streams_12_full_n;
        else 
            pe_streams_12_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_12_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_12_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_C))) then 
            pe_streams_12_write <= ap_const_logic_1;
        else 
            pe_streams_12_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_13_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_13_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_grp2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_D))) then 
            pe_streams_13_blk_n <= pe_streams_13_full_n;
        else 
            pe_streams_13_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_13_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_13_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_D))) then 
            pe_streams_13_write <= ap_const_logic_1;
        else 
            pe_streams_13_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_14_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_14_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_E))) then 
            pe_streams_14_blk_n <= pe_streams_14_full_n;
        else 
            pe_streams_14_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_14_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_14_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_E))) then 
            pe_streams_14_write <= ap_const_logic_1;
        else 
            pe_streams_14_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_15_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_15_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp16_done_reg, ap_block_pp0_stage0_grp16)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp16) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_F))) then 
            pe_streams_15_blk_n <= pe_streams_15_full_n;
        else 
            pe_streams_15_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_15_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_15_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp16_done_reg, ap_block_pp0_stage0_11001_grp16)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp16) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp16_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_F))) then 
            pe_streams_15_write <= ap_const_logic_1;
        else 
            pe_streams_15_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_1_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp14_done_reg, ap_block_pp0_stage0_grp14)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp14) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_1))) then 
            pe_streams_1_blk_n <= pe_streams_1_full_n;
        else 
            pe_streams_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_1_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp14_done_reg, ap_block_pp0_stage0_11001_grp14)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp14) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp14_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_1))) then 
            pe_streams_1_write <= ap_const_logic_1;
        else 
            pe_streams_1_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_2_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp13_done_reg, ap_block_pp0_stage0_grp13)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp13) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_2))) then 
            pe_streams_2_blk_n <= pe_streams_2_full_n;
        else 
            pe_streams_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_2_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp13_done_reg, ap_block_pp0_stage0_11001_grp13)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp13) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp13_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_2))) then 
            pe_streams_2_write <= ap_const_logic_1;
        else 
            pe_streams_2_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_3_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_3_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp12_done_reg, ap_block_pp0_stage0_grp12)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp12) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_3))) then 
            pe_streams_3_blk_n <= pe_streams_3_full_n;
        else 
            pe_streams_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_3_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_3_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp12_done_reg, ap_block_pp0_stage0_11001_grp12)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp12) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp12_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_3))) then 
            pe_streams_3_write <= ap_const_logic_1;
        else 
            pe_streams_3_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_4_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp11_done_reg, ap_block_pp0_stage0_grp11)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp11) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_4))) then 
            pe_streams_4_blk_n <= pe_streams_4_full_n;
        else 
            pe_streams_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_4_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp11_done_reg, ap_block_pp0_stage0_11001_grp11)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp11) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp11_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_4))) then 
            pe_streams_4_write <= ap_const_logic_1;
        else 
            pe_streams_4_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_5_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_5_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp10_done_reg, ap_block_pp0_stage0_grp10)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_5))) then 
            pe_streams_5_blk_n <= pe_streams_5_full_n;
        else 
            pe_streams_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_5_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_5_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp10_done_reg, ap_block_pp0_stage0_11001_grp10)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp10) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp10_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_5))) then 
            pe_streams_5_write <= ap_const_logic_1;
        else 
            pe_streams_5_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_6_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_6_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_pp0_stage0_grp9)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_6))) then 
            pe_streams_6_blk_n <= pe_streams_6_full_n;
        else 
            pe_streams_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_6_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_6_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_pp0_stage0_11001_grp9)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_6))) then 
            pe_streams_6_write <= ap_const_logic_1;
        else 
            pe_streams_6_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_7_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_7_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_block_pp0_stage0_grp8)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_7))) then 
            pe_streams_7_blk_n <= pe_streams_7_full_n;
        else 
            pe_streams_7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_7_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_7_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp8_done_reg, ap_block_pp0_stage0_11001_grp8)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp8_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_7))) then 
            pe_streams_7_write <= ap_const_logic_1;
        else 
            pe_streams_7_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_8_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_8_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_pp0_stage0_grp7)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_8))) then 
            pe_streams_8_blk_n <= pe_streams_8_full_n;
        else 
            pe_streams_8_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_8_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_8_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_pp0_stage0_11001_grp7)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_8))) then 
            pe_streams_8_write <= ap_const_logic_1;
        else 
            pe_streams_8_write <= ap_const_logic_0;
        end if; 
    end process;


    pe_streams_9_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, pe_streams_9_full_n, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_grp6)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_9))) then 
            pe_streams_9_blk_n <= pe_streams_9_full_n;
        else 
            pe_streams_9_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pe_streams_9_din <= ap_const_lv97_1000000000000000000000000;

    pe_streams_9_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln230_reg_265, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_11001_grp6)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg) and (trunc_ln230_reg_265 = ap_const_lv4_9))) then 
            pe_streams_9_write <= ap_const_logic_1;
        else 
            pe_streams_9_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln230_fu_246_p1 <= ap_sig_allocacmp_i_1(4 - 1 downto 0);
end behav;
