-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spmv_csc_entry_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    num_rows : IN STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c_full_n : IN STD_LOGIC;
    num_rows_c_write : OUT STD_LOGIC;
    num_rows_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c2_full_n : IN STD_LOGIC;
    num_rows_c2_write : OUT STD_LOGIC;
    num_rows_c2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c3_full_n : IN STD_LOGIC;
    num_rows_c3_write : OUT STD_LOGIC;
    num_rows_c3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c4_full_n : IN STD_LOGIC;
    num_rows_c4_write : OUT STD_LOGIC;
    num_rows_c4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c5_full_n : IN STD_LOGIC;
    num_rows_c5_write : OUT STD_LOGIC;
    num_rows_c5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c6_full_n : IN STD_LOGIC;
    num_rows_c6_write : OUT STD_LOGIC;
    num_rows_c6_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c6_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c7_full_n : IN STD_LOGIC;
    num_rows_c7_write : OUT STD_LOGIC;
    num_rows_c7_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c7_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c8_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c8_full_n : IN STD_LOGIC;
    num_rows_c8_write : OUT STD_LOGIC;
    num_rows_c8_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c8_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c9_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c9_full_n : IN STD_LOGIC;
    num_rows_c9_write : OUT STD_LOGIC;
    num_rows_c9_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c9_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c10_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c10_full_n : IN STD_LOGIC;
    num_rows_c10_write : OUT STD_LOGIC;
    num_rows_c10_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c10_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c11_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c11_full_n : IN STD_LOGIC;
    num_rows_c11_write : OUT STD_LOGIC;
    num_rows_c11_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c11_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c12_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c12_full_n : IN STD_LOGIC;
    num_rows_c12_write : OUT STD_LOGIC;
    num_rows_c12_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c12_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c13_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c13_full_n : IN STD_LOGIC;
    num_rows_c13_write : OUT STD_LOGIC;
    num_rows_c13_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c13_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c14_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c14_full_n : IN STD_LOGIC;
    num_rows_c14_write : OUT STD_LOGIC;
    num_rows_c14_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c14_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c15_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c15_full_n : IN STD_LOGIC;
    num_rows_c15_write : OUT STD_LOGIC;
    num_rows_c15_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c15_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c16_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_rows_c16_full_n : IN STD_LOGIC;
    num_rows_c16_write : OUT STD_LOGIC;
    num_rows_c16_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_rows_c16_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of spmv_csc_entry_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal num_rows_c_blk_n : STD_LOGIC;
    signal num_rows_c2_blk_n : STD_LOGIC;
    signal num_rows_c3_blk_n : STD_LOGIC;
    signal num_rows_c4_blk_n : STD_LOGIC;
    signal num_rows_c5_blk_n : STD_LOGIC;
    signal num_rows_c6_blk_n : STD_LOGIC;
    signal num_rows_c7_blk_n : STD_LOGIC;
    signal num_rows_c8_blk_n : STD_LOGIC;
    signal num_rows_c9_blk_n : STD_LOGIC;
    signal num_rows_c10_blk_n : STD_LOGIC;
    signal num_rows_c11_blk_n : STD_LOGIC;
    signal num_rows_c12_blk_n : STD_LOGIC;
    signal num_rows_c13_blk_n : STD_LOGIC;
    signal num_rows_c14_blk_n : STD_LOGIC;
    signal num_rows_c15_blk_n : STD_LOGIC;
    signal num_rows_c16_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, num_rows_c_full_n, num_rows_c2_full_n, num_rows_c3_full_n, num_rows_c4_full_n, num_rows_c5_full_n, num_rows_c6_full_n, num_rows_c7_full_n, num_rows_c8_full_n, num_rows_c9_full_n, num_rows_c10_full_n, num_rows_c11_full_n, num_rows_c12_full_n, num_rows_c13_full_n, num_rows_c14_full_n, num_rows_c15_full_n, num_rows_c16_full_n)
    begin
                ap_block_state1 <= ((num_rows_c13_full_n = ap_const_logic_0) or (num_rows_c12_full_n = ap_const_logic_0) or (num_rows_c11_full_n = ap_const_logic_0) or (num_rows_c10_full_n = ap_const_logic_0) or (num_rows_c9_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (num_rows_c8_full_n = ap_const_logic_0) or (num_rows_c7_full_n = ap_const_logic_0) or (num_rows_c6_full_n = ap_const_logic_0) or (num_rows_c5_full_n = ap_const_logic_0) or (num_rows_c4_full_n = ap_const_logic_0) or (num_rows_c3_full_n = ap_const_logic_0) or (num_rows_c2_full_n = ap_const_logic_0) or (num_rows_c_full_n = ap_const_logic_0) or (num_rows_c16_full_n = ap_const_logic_0) or (num_rows_c15_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (num_rows_c14_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c10_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c10_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c10_blk_n <= num_rows_c10_full_n;
        else 
            num_rows_c10_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c10_din <= num_rows;

    num_rows_c10_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c10_write <= ap_const_logic_1;
        else 
            num_rows_c10_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c11_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c11_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c11_blk_n <= num_rows_c11_full_n;
        else 
            num_rows_c11_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c11_din <= num_rows;

    num_rows_c11_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c11_write <= ap_const_logic_1;
        else 
            num_rows_c11_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c12_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c12_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c12_blk_n <= num_rows_c12_full_n;
        else 
            num_rows_c12_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c12_din <= num_rows;

    num_rows_c12_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c12_write <= ap_const_logic_1;
        else 
            num_rows_c12_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c13_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c13_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c13_blk_n <= num_rows_c13_full_n;
        else 
            num_rows_c13_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c13_din <= num_rows;

    num_rows_c13_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c13_write <= ap_const_logic_1;
        else 
            num_rows_c13_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c14_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c14_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c14_blk_n <= num_rows_c14_full_n;
        else 
            num_rows_c14_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c14_din <= num_rows;

    num_rows_c14_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c14_write <= ap_const_logic_1;
        else 
            num_rows_c14_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c15_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c15_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c15_blk_n <= num_rows_c15_full_n;
        else 
            num_rows_c15_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c15_din <= num_rows;

    num_rows_c15_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c15_write <= ap_const_logic_1;
        else 
            num_rows_c15_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c16_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c16_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c16_blk_n <= num_rows_c16_full_n;
        else 
            num_rows_c16_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c16_din <= num_rows;

    num_rows_c16_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c16_write <= ap_const_logic_1;
        else 
            num_rows_c16_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c2_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c2_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c2_blk_n <= num_rows_c2_full_n;
        else 
            num_rows_c2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c2_din <= num_rows;

    num_rows_c2_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c2_write <= ap_const_logic_1;
        else 
            num_rows_c2_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c3_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c3_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c3_blk_n <= num_rows_c3_full_n;
        else 
            num_rows_c3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c3_din <= num_rows;

    num_rows_c3_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c3_write <= ap_const_logic_1;
        else 
            num_rows_c3_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c4_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c4_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c4_blk_n <= num_rows_c4_full_n;
        else 
            num_rows_c4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c4_din <= num_rows;

    num_rows_c4_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c4_write <= ap_const_logic_1;
        else 
            num_rows_c4_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c5_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c5_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c5_blk_n <= num_rows_c5_full_n;
        else 
            num_rows_c5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c5_din <= num_rows;

    num_rows_c5_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c5_write <= ap_const_logic_1;
        else 
            num_rows_c5_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c6_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c6_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c6_blk_n <= num_rows_c6_full_n;
        else 
            num_rows_c6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c6_din <= num_rows;

    num_rows_c6_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c6_write <= ap_const_logic_1;
        else 
            num_rows_c6_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c7_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c7_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c7_blk_n <= num_rows_c7_full_n;
        else 
            num_rows_c7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c7_din <= num_rows;

    num_rows_c7_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c7_write <= ap_const_logic_1;
        else 
            num_rows_c7_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c8_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c8_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c8_blk_n <= num_rows_c8_full_n;
        else 
            num_rows_c8_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c8_din <= num_rows;

    num_rows_c8_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c8_write <= ap_const_logic_1;
        else 
            num_rows_c8_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c9_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c9_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c9_blk_n <= num_rows_c9_full_n;
        else 
            num_rows_c9_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c9_din <= num_rows;

    num_rows_c9_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c9_write <= ap_const_logic_1;
        else 
            num_rows_c9_write <= ap_const_logic_0;
        end if; 
    end process;


    num_rows_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_rows_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_rows_c_blk_n <= num_rows_c_full_n;
        else 
            num_rows_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_rows_c_din <= num_rows;

    num_rows_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            num_rows_c_write <= ap_const_logic_1;
        else 
            num_rows_c_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
