-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spmv_csc_read_col_info_Pipeline_VITIS_LOOP_46_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem3_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem3_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem3_0_WREADY : IN STD_LOGIC;
    m_axi_gmem3_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem3_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem3_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem3_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_RVALID : IN STD_LOGIC;
    m_axi_gmem3_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem3_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_0_RLAST : IN STD_LOGIC;
    m_axi_gmem3_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem3_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_BVALID : IN STD_LOGIC;
    m_axi_gmem3_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem3_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    col_info_stream_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    col_info_stream_full_n : IN STD_LOGIC;
    col_info_stream_write : OUT STD_LOGIC;
    col_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    col_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    x_element : IN STD_LOGIC_VECTOR (31 downto 0);
    prev : IN STD_LOGIC_VECTOR (31 downto 0);
    sub : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln46_1 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln46 : IN STD_LOGIC_VECTOR (61 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    prev_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    prev_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of spmv_csc_read_col_info_Pipeline_VITIS_LOOP_46_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln53_reg_289 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_pp0_stage0_iter3_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln46_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem3_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal col_info_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln46_reg_274 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln46_reg_274_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal prev_2_reg_278 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_nnz_fu_203_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_nnz_reg_284 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln53_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_element_1_reg_293 : STD_LOGIC_VECTOR (31 downto 0);
    signal prev_1_fu_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal empty_fu_72 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal col_fu_76 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln46_fu_177_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_sig_allocacmp_col_load : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal zext_ln46_fu_167_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component spmv_csc_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component spmv_csc_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    col_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln46_fu_171_p2 = ap_const_lv1_1))) then 
                    col_fu_76 <= add_ln46_fu_177_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_fu_76 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_fu_72 <= x_element;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    empty_fu_72 <= x_element_1_reg_293;
                end if;
            end if; 
        end if;
    end process;

    prev_1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    prev_1_fu_68 <= prev;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    prev_1_fu_68 <= prev_2_reg_278;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln46_reg_274 <= icmp_ln46_fu_171_p2;
                icmp_ln46_reg_274_pp0_iter1_reg <= icmp_ln46_reg_274;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                col_nnz_reg_284 <= col_nnz_fu_203_p2;
                icmp_ln53_reg_289 <= icmp_ln53_fu_208_p2;
                x_element_1_reg_293 <= m_axi_gmem3_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                prev_2_reg_278 <= m_axi_gmem1_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln46_fu_177_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_col_load) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, m_axi_gmem1_0_RVALID, m_axi_gmem3_0_RVALID, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem3_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem1_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, m_axi_gmem1_0_RVALID, m_axi_gmem3_0_RVALID, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem3_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem1_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, m_axi_gmem1_0_RVALID, m_axi_gmem3_0_RVALID, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem3_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem1_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, m_axi_gmem1_0_RVALID, m_axi_gmem3_0_RVALID, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem3_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem1_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter3_grp1_assign_proc : process(col_info_stream_full_n, icmp_ln53_reg_289)
    begin
                ap_block_state4_pp0_stage0_iter3_grp1 <= ((icmp_ln53_reg_289 = ap_const_lv1_1) and (col_info_stream_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln46_fu_171_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_fu_171_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, col_fu_76, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_col_load <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_col_load <= col_fu_76;
        end if; 
    end process;


    col_info_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, col_info_stream_full_n, icmp_ln53_reg_289, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln53_reg_289 = ap_const_lv1_1))) then 
            col_info_stream_blk_n <= col_info_stream_full_n;
        else 
            col_info_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    col_info_stream_din <= (empty_fu_72 & col_nnz_reg_284);

    col_info_stream_write_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln53_reg_289, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln53_reg_289 = ap_const_lv1_1))) then 
            col_info_stream_write <= ap_const_logic_1;
        else 
            col_info_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    col_nnz_fu_203_p2 <= std_logic_vector(unsigned(prev_2_reg_278) - unsigned(prev_1_fu_68));

    gmem1_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem1_blk_n_R <= m_axi_gmem1_0_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem3_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem3_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem3_blk_n_R <= m_axi_gmem3_0_RVALID;
        else 
            gmem3_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln46_fu_171_p2 <= "1" when (signed(zext_ln46_fu_167_p1) < signed(sub)) else "0";
    icmp_ln53_fu_208_p2 <= "1" when (signed(col_nnz_fu_203_p2) > signed(ap_const_lv32_0)) else "0";
    m_axi_gmem1_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_ARID <= ap_const_lv1_0;
    m_axi_gmem1_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_AWID <= ap_const_lv1_0;
    m_axi_gmem1_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_0_BREADY <= ap_const_logic_0;

    m_axi_gmem1_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem1_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_0_WID <= ap_const_lv1_0;
    m_axi_gmem1_0_WLAST <= ap_const_logic_0;
    m_axi_gmem1_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_WVALID <= ap_const_logic_0;
    m_axi_gmem3_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem3_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem3_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem3_0_ARID <= ap_const_lv1_0;
    m_axi_gmem3_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem3_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem3_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem3_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem3_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem3_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem3_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem3_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem3_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem3_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem3_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem3_0_AWID <= ap_const_lv1_0;
    m_axi_gmem3_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem3_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem3_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem3_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem3_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem3_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem3_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem3_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem3_0_BREADY <= ap_const_logic_0;

    m_axi_gmem3_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem3_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem3_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem3_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem3_0_WID <= ap_const_lv1_0;
    m_axi_gmem3_0_WLAST <= ap_const_logic_0;
    m_axi_gmem3_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem3_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem3_0_WVALID <= ap_const_logic_0;
    p_out <= empty_fu_72;

    p_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp1, icmp_ln46_reg_274_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln46_reg_274_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    prev_1_out <= prev_1_fu_68;

    prev_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp1, icmp_ln46_reg_274_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln46_reg_274_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            prev_1_out_ap_vld <= ap_const_logic_1;
        else 
            prev_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln46_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_col_load),32));
end behav;
