// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module spmv_csc_distribute_to_pe_Pipeline_VITIS_LOOP_230_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pe_streams_14_din,
        pe_streams_14_full_n,
        pe_streams_14_write,
        pe_streams_14_num_data_valid,
        pe_streams_14_fifo_cap,
        pe_streams_13_din,
        pe_streams_13_full_n,
        pe_streams_13_write,
        pe_streams_13_num_data_valid,
        pe_streams_13_fifo_cap,
        pe_streams_12_din,
        pe_streams_12_full_n,
        pe_streams_12_write,
        pe_streams_12_num_data_valid,
        pe_streams_12_fifo_cap,
        pe_streams_11_din,
        pe_streams_11_full_n,
        pe_streams_11_write,
        pe_streams_11_num_data_valid,
        pe_streams_11_fifo_cap,
        pe_streams_10_din,
        pe_streams_10_full_n,
        pe_streams_10_write,
        pe_streams_10_num_data_valid,
        pe_streams_10_fifo_cap,
        pe_streams_9_din,
        pe_streams_9_full_n,
        pe_streams_9_write,
        pe_streams_9_num_data_valid,
        pe_streams_9_fifo_cap,
        pe_streams_8_din,
        pe_streams_8_full_n,
        pe_streams_8_write,
        pe_streams_8_num_data_valid,
        pe_streams_8_fifo_cap,
        pe_streams_7_din,
        pe_streams_7_full_n,
        pe_streams_7_write,
        pe_streams_7_num_data_valid,
        pe_streams_7_fifo_cap,
        pe_streams_6_din,
        pe_streams_6_full_n,
        pe_streams_6_write,
        pe_streams_6_num_data_valid,
        pe_streams_6_fifo_cap,
        pe_streams_5_din,
        pe_streams_5_full_n,
        pe_streams_5_write,
        pe_streams_5_num_data_valid,
        pe_streams_5_fifo_cap,
        pe_streams_4_din,
        pe_streams_4_full_n,
        pe_streams_4_write,
        pe_streams_4_num_data_valid,
        pe_streams_4_fifo_cap,
        pe_streams_3_din,
        pe_streams_3_full_n,
        pe_streams_3_write,
        pe_streams_3_num_data_valid,
        pe_streams_3_fifo_cap,
        pe_streams_2_din,
        pe_streams_2_full_n,
        pe_streams_2_write,
        pe_streams_2_num_data_valid,
        pe_streams_2_fifo_cap,
        pe_streams_1_din,
        pe_streams_1_full_n,
        pe_streams_1_write,
        pe_streams_1_num_data_valid,
        pe_streams_1_fifo_cap,
        pe_streams_0_din,
        pe_streams_0_full_n,
        pe_streams_0_write,
        pe_streams_0_num_data_valid,
        pe_streams_0_fifo_cap,
        pe_streams_15_din,
        pe_streams_15_full_n,
        pe_streams_15_write,
        pe_streams_15_num_data_valid,
        pe_streams_15_fifo_cap
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [96:0] pe_streams_14_din;
input   pe_streams_14_full_n;
output   pe_streams_14_write;
input  [31:0] pe_streams_14_num_data_valid;
input  [31:0] pe_streams_14_fifo_cap;
output  [96:0] pe_streams_13_din;
input   pe_streams_13_full_n;
output   pe_streams_13_write;
input  [31:0] pe_streams_13_num_data_valid;
input  [31:0] pe_streams_13_fifo_cap;
output  [96:0] pe_streams_12_din;
input   pe_streams_12_full_n;
output   pe_streams_12_write;
input  [31:0] pe_streams_12_num_data_valid;
input  [31:0] pe_streams_12_fifo_cap;
output  [96:0] pe_streams_11_din;
input   pe_streams_11_full_n;
output   pe_streams_11_write;
input  [31:0] pe_streams_11_num_data_valid;
input  [31:0] pe_streams_11_fifo_cap;
output  [96:0] pe_streams_10_din;
input   pe_streams_10_full_n;
output   pe_streams_10_write;
input  [31:0] pe_streams_10_num_data_valid;
input  [31:0] pe_streams_10_fifo_cap;
output  [96:0] pe_streams_9_din;
input   pe_streams_9_full_n;
output   pe_streams_9_write;
input  [31:0] pe_streams_9_num_data_valid;
input  [31:0] pe_streams_9_fifo_cap;
output  [96:0] pe_streams_8_din;
input   pe_streams_8_full_n;
output   pe_streams_8_write;
input  [31:0] pe_streams_8_num_data_valid;
input  [31:0] pe_streams_8_fifo_cap;
output  [96:0] pe_streams_7_din;
input   pe_streams_7_full_n;
output   pe_streams_7_write;
input  [31:0] pe_streams_7_num_data_valid;
input  [31:0] pe_streams_7_fifo_cap;
output  [96:0] pe_streams_6_din;
input   pe_streams_6_full_n;
output   pe_streams_6_write;
input  [31:0] pe_streams_6_num_data_valid;
input  [31:0] pe_streams_6_fifo_cap;
output  [96:0] pe_streams_5_din;
input   pe_streams_5_full_n;
output   pe_streams_5_write;
input  [31:0] pe_streams_5_num_data_valid;
input  [31:0] pe_streams_5_fifo_cap;
output  [96:0] pe_streams_4_din;
input   pe_streams_4_full_n;
output   pe_streams_4_write;
input  [31:0] pe_streams_4_num_data_valid;
input  [31:0] pe_streams_4_fifo_cap;
output  [96:0] pe_streams_3_din;
input   pe_streams_3_full_n;
output   pe_streams_3_write;
input  [31:0] pe_streams_3_num_data_valid;
input  [31:0] pe_streams_3_fifo_cap;
output  [96:0] pe_streams_2_din;
input   pe_streams_2_full_n;
output   pe_streams_2_write;
input  [31:0] pe_streams_2_num_data_valid;
input  [31:0] pe_streams_2_fifo_cap;
output  [96:0] pe_streams_1_din;
input   pe_streams_1_full_n;
output   pe_streams_1_write;
input  [31:0] pe_streams_1_num_data_valid;
input  [31:0] pe_streams_1_fifo_cap;
output  [96:0] pe_streams_0_din;
input   pe_streams_0_full_n;
output   pe_streams_0_write;
input  [31:0] pe_streams_0_num_data_valid;
input  [31:0] pe_streams_0_fifo_cap;
output  [96:0] pe_streams_15_din;
input   pe_streams_15_full_n;
output   pe_streams_15_write;
input  [31:0] pe_streams_15_num_data_valid;
input  [31:0] pe_streams_15_fifo_cap;

reg ap_idle;
reg pe_streams_14_write;
reg pe_streams_13_write;
reg pe_streams_12_write;
reg pe_streams_11_write;
reg pe_streams_10_write;
reg pe_streams_9_write;
reg pe_streams_8_write;
reg pe_streams_7_write;
reg pe_streams_6_write;
reg pe_streams_5_write;
reg pe_streams_4_write;
reg pe_streams_3_write;
reg pe_streams_2_write;
reg pe_streams_1_write;
reg pe_streams_0_write;
reg pe_streams_15_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [3:0] trunc_ln230_reg_265;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_state2_pp0_stage0_iter1_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg    ap_block_state2_pp0_stage0_iter1_grp3;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
reg    ap_block_state2_pp0_stage0_iter1_grp4;
reg    ap_block_pp0_stage0_subdone_grp4_done_reg;
reg    ap_block_pp0_stage0_subdone_grp4;
reg    ap_block_state2_pp0_stage0_iter1_grp5;
reg    ap_block_pp0_stage0_subdone_grp5_done_reg;
reg    ap_block_pp0_stage0_subdone_grp5;
reg    ap_block_state2_pp0_stage0_iter1_grp6;
reg    ap_block_pp0_stage0_subdone_grp6_done_reg;
reg    ap_block_pp0_stage0_subdone_grp6;
reg    ap_block_state2_pp0_stage0_iter1_grp7;
reg    ap_block_pp0_stage0_subdone_grp7_done_reg;
reg    ap_block_pp0_stage0_subdone_grp7;
reg    ap_block_state2_pp0_stage0_iter1_grp8;
reg    ap_block_pp0_stage0_subdone_grp8_done_reg;
reg    ap_block_pp0_stage0_subdone_grp8;
reg    ap_block_state2_pp0_stage0_iter1_grp9;
reg    ap_block_pp0_stage0_subdone_grp9_done_reg;
reg    ap_block_pp0_stage0_subdone_grp9;
reg    ap_block_state2_pp0_stage0_iter1_grp10;
reg    ap_block_pp0_stage0_subdone_grp10_done_reg;
reg    ap_block_pp0_stage0_subdone_grp10;
reg    ap_block_state2_pp0_stage0_iter1_grp11;
reg    ap_block_pp0_stage0_subdone_grp11_done_reg;
reg    ap_block_pp0_stage0_subdone_grp11;
reg    ap_block_state2_pp0_stage0_iter1_grp12;
reg    ap_block_pp0_stage0_subdone_grp12_done_reg;
reg    ap_block_pp0_stage0_subdone_grp12;
reg    ap_block_state2_pp0_stage0_iter1_grp13;
reg    ap_block_pp0_stage0_subdone_grp13_done_reg;
reg    ap_block_pp0_stage0_subdone_grp13;
reg    ap_block_state2_pp0_stage0_iter1_grp14;
reg    ap_block_pp0_stage0_subdone_grp14_done_reg;
reg    ap_block_pp0_stage0_subdone_grp14;
reg    ap_block_state2_pp0_stage0_iter1_grp15;
reg    ap_block_pp0_stage0_subdone_grp15_done_reg;
reg    ap_block_pp0_stage0_subdone_grp15;
reg    ap_block_state2_pp0_stage0_iter1_grp16;
reg    ap_block_pp0_stage0_subdone_grp16_done_reg;
reg    ap_block_pp0_stage0_subdone_grp16;
wire   [0:0] icmp_ln230_fu_234_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    pe_streams_0_blk_n;
wire    ap_block_pp0_stage0_grp15;
reg    pe_streams_1_blk_n;
wire    ap_block_pp0_stage0_grp14;
reg    pe_streams_2_blk_n;
wire    ap_block_pp0_stage0_grp13;
reg    pe_streams_3_blk_n;
wire    ap_block_pp0_stage0_grp12;
reg    pe_streams_4_blk_n;
wire    ap_block_pp0_stage0_grp11;
reg    pe_streams_5_blk_n;
wire    ap_block_pp0_stage0_grp10;
reg    pe_streams_6_blk_n;
wire    ap_block_pp0_stage0_grp9;
reg    pe_streams_7_blk_n;
wire    ap_block_pp0_stage0_grp8;
reg    pe_streams_8_blk_n;
wire    ap_block_pp0_stage0_grp7;
reg    pe_streams_9_blk_n;
wire    ap_block_pp0_stage0_grp6;
reg    pe_streams_10_blk_n;
wire    ap_block_pp0_stage0_grp5;
reg    pe_streams_11_blk_n;
wire    ap_block_pp0_stage0_grp4;
reg    pe_streams_12_blk_n;
wire    ap_block_pp0_stage0_grp3;
reg    pe_streams_13_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg    pe_streams_14_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    pe_streams_15_blk_n;
wire    ap_block_pp0_stage0_grp16;
wire   [3:0] trunc_ln230_fu_246_p1;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] i_fu_94;
wire   [4:0] add_ln230_fu_240_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_01001_grp2;
reg    ap_block_pp0_stage0_11001_grp2;
reg    ap_block_pp0_stage0_01001_grp3;
reg    ap_block_pp0_stage0_11001_grp3;
reg    ap_block_pp0_stage0_01001_grp4;
reg    ap_block_pp0_stage0_11001_grp4;
reg    ap_block_pp0_stage0_01001_grp5;
reg    ap_block_pp0_stage0_11001_grp5;
reg    ap_block_pp0_stage0_01001_grp6;
reg    ap_block_pp0_stage0_11001_grp6;
reg    ap_block_pp0_stage0_01001_grp7;
reg    ap_block_pp0_stage0_11001_grp7;
reg    ap_block_pp0_stage0_01001_grp8;
reg    ap_block_pp0_stage0_11001_grp8;
reg    ap_block_pp0_stage0_01001_grp9;
reg    ap_block_pp0_stage0_11001_grp9;
reg    ap_block_pp0_stage0_01001_grp10;
reg    ap_block_pp0_stage0_11001_grp10;
reg    ap_block_pp0_stage0_01001_grp11;
reg    ap_block_pp0_stage0_11001_grp11;
reg    ap_block_pp0_stage0_01001_grp12;
reg    ap_block_pp0_stage0_11001_grp12;
reg    ap_block_pp0_stage0_01001_grp13;
reg    ap_block_pp0_stage0_11001_grp13;
reg    ap_block_pp0_stage0_01001_grp14;
reg    ap_block_pp0_stage0_11001_grp14;
reg    ap_block_pp0_stage0_01001_grp15;
reg    ap_block_pp0_stage0_11001_grp15;
reg    ap_block_pp0_stage0_01001_grp16;
reg    ap_block_pp0_stage0_11001_grp16;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp7_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp8_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp9_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp10_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp11_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp12_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp13_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp14_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp15_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp16_done_reg = 1'b0;
#0 i_fu_94 = 5'd0;
#0 ap_done_reg = 1'b0;
end

spmv_csc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp10_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp10_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp10)) begin
            ap_block_pp0_stage0_subdone_grp10_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp11_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp11_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp11)) begin
            ap_block_pp0_stage0_subdone_grp11_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp12_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp12_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp12)) begin
            ap_block_pp0_stage0_subdone_grp12_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp13_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp13_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp13)) begin
            ap_block_pp0_stage0_subdone_grp13_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp14_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp14_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp14)) begin
            ap_block_pp0_stage0_subdone_grp14_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp15_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp15_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp15)) begin
            ap_block_pp0_stage0_subdone_grp15_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp16_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp16_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp16)) begin
            ap_block_pp0_stage0_subdone_grp16_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
            ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp4)) begin
            ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp5)) begin
            ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp6)) begin
            ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp7)) begin
            ap_block_pp0_stage0_subdone_grp7_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp8)) begin
            ap_block_pp0_stage0_subdone_grp8_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp9_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp9_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp9)) begin
            ap_block_pp0_stage0_subdone_grp9_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln230_fu_234_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_94 <= add_ln230_fu_240_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_94 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln230_reg_265 <= trunc_ln230_fu_246_p1;
    end
end

always @ (*) begin
    if (((icmp_ln230_fu_234_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_94;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp15) & (1'b0 == ap_block_pp0_stage0_subdone_grp15_done_reg) & (trunc_ln230_reg_265 == 4'd0))) begin
        pe_streams_0_blk_n = pe_streams_0_full_n;
    end else begin
        pe_streams_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp15) & (1'b0 == ap_block_pp0_stage0_subdone_grp15_done_reg) & (trunc_ln230_reg_265 == 4'd0))) begin
        pe_streams_0_write = 1'b1;
    end else begin
        pe_streams_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (trunc_ln230_reg_265 == 4'd10))) begin
        pe_streams_10_blk_n = pe_streams_10_full_n;
    end else begin
        pe_streams_10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (trunc_ln230_reg_265 == 4'd10))) begin
        pe_streams_10_write = 1'b1;
    end else begin
        pe_streams_10_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (trunc_ln230_reg_265 == 4'd11))) begin
        pe_streams_11_blk_n = pe_streams_11_full_n;
    end else begin
        pe_streams_11_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (trunc_ln230_reg_265 == 4'd11))) begin
        pe_streams_11_write = 1'b1;
    end else begin
        pe_streams_11_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (trunc_ln230_reg_265 == 4'd12))) begin
        pe_streams_12_blk_n = pe_streams_12_full_n;
    end else begin
        pe_streams_12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (trunc_ln230_reg_265 == 4'd12))) begin
        pe_streams_12_write = 1'b1;
    end else begin
        pe_streams_12_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (trunc_ln230_reg_265 == 4'd13))) begin
        pe_streams_13_blk_n = pe_streams_13_full_n;
    end else begin
        pe_streams_13_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (trunc_ln230_reg_265 == 4'd13))) begin
        pe_streams_13_write = 1'b1;
    end else begin
        pe_streams_13_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (trunc_ln230_reg_265 == 4'd14))) begin
        pe_streams_14_blk_n = pe_streams_14_full_n;
    end else begin
        pe_streams_14_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (trunc_ln230_reg_265 == 4'd14))) begin
        pe_streams_14_write = 1'b1;
    end else begin
        pe_streams_14_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp16) & (1'b0 == ap_block_pp0_stage0_subdone_grp16_done_reg) & (trunc_ln230_reg_265 == 4'd15))) begin
        pe_streams_15_blk_n = pe_streams_15_full_n;
    end else begin
        pe_streams_15_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp16) & (1'b0 == ap_block_pp0_stage0_subdone_grp16_done_reg) & (trunc_ln230_reg_265 == 4'd15))) begin
        pe_streams_15_write = 1'b1;
    end else begin
        pe_streams_15_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg) & (trunc_ln230_reg_265 == 4'd1))) begin
        pe_streams_1_blk_n = pe_streams_1_full_n;
    end else begin
        pe_streams_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg) & (trunc_ln230_reg_265 == 4'd1))) begin
        pe_streams_1_write = 1'b1;
    end else begin
        pe_streams_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg) & (trunc_ln230_reg_265 == 4'd2))) begin
        pe_streams_2_blk_n = pe_streams_2_full_n;
    end else begin
        pe_streams_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg) & (trunc_ln230_reg_265 == 4'd2))) begin
        pe_streams_2_write = 1'b1;
    end else begin
        pe_streams_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg) & (trunc_ln230_reg_265 == 4'd3))) begin
        pe_streams_3_blk_n = pe_streams_3_full_n;
    end else begin
        pe_streams_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg) & (trunc_ln230_reg_265 == 4'd3))) begin
        pe_streams_3_write = 1'b1;
    end else begin
        pe_streams_3_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg) & (trunc_ln230_reg_265 == 4'd4))) begin
        pe_streams_4_blk_n = pe_streams_4_full_n;
    end else begin
        pe_streams_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg) & (trunc_ln230_reg_265 == 4'd4))) begin
        pe_streams_4_write = 1'b1;
    end else begin
        pe_streams_4_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp10) & (1'b0 == ap_block_pp0_stage0_subdone_grp10_done_reg) & (trunc_ln230_reg_265 == 4'd5))) begin
        pe_streams_5_blk_n = pe_streams_5_full_n;
    end else begin
        pe_streams_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp10) & (1'b0 == ap_block_pp0_stage0_subdone_grp10_done_reg) & (trunc_ln230_reg_265 == 4'd5))) begin
        pe_streams_5_write = 1'b1;
    end else begin
        pe_streams_5_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp9) & (1'b0 == ap_block_pp0_stage0_subdone_grp9_done_reg) & (trunc_ln230_reg_265 == 4'd6))) begin
        pe_streams_6_blk_n = pe_streams_6_full_n;
    end else begin
        pe_streams_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp9) & (1'b0 == ap_block_pp0_stage0_subdone_grp9_done_reg) & (trunc_ln230_reg_265 == 4'd6))) begin
        pe_streams_6_write = 1'b1;
    end else begin
        pe_streams_6_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (trunc_ln230_reg_265 == 4'd7))) begin
        pe_streams_7_blk_n = pe_streams_7_full_n;
    end else begin
        pe_streams_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg) & (trunc_ln230_reg_265 == 4'd7))) begin
        pe_streams_7_write = 1'b1;
    end else begin
        pe_streams_7_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg) & (trunc_ln230_reg_265 == 4'd8))) begin
        pe_streams_8_blk_n = pe_streams_8_full_n;
    end else begin
        pe_streams_8_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg) & (trunc_ln230_reg_265 == 4'd8))) begin
        pe_streams_8_write = 1'b1;
    end else begin
        pe_streams_8_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg) & (trunc_ln230_reg_265 == 4'd9))) begin
        pe_streams_9_blk_n = pe_streams_9_full_n;
    end else begin
        pe_streams_9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg) & (trunc_ln230_reg_265 == 4'd9))) begin
        pe_streams_9_write = 1'b1;
    end else begin
        pe_streams_9_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln230_fu_240_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp10 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp10) & (1'b0 == ap_block_pp0_stage0_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp11 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp12 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp13 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp14 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp15 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp15) & (1'b0 == ap_block_pp0_stage0_subdone_grp15_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp16) & (1'b0 == ap_block_pp0_stage0_subdone_grp16_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp3 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp4 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp5 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp6 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp7 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp9 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp9) & (1'b0 == ap_block_pp0_stage0_subdone_grp9_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b1 == ap_block_state2_pp0_stage0_iter1_grp16) & (1'b0 == ap_block_pp0_stage0_subdone_grp16_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp15) & (1'b0 == ap_block_pp0_stage0_subdone_grp15_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp10) & (1'b0 == ap_block_pp0_stage0_subdone_grp10_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp9) & (1'b0 == ap_block_pp0_stage0_subdone_grp9_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp7) 
    & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp10 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp10) & (1'b0 == ap_block_pp0_stage0_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp11 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp12 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp13 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp14 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp15 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp15) & (1'b0 == ap_block_pp0_stage0_subdone_grp15_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp16) & (1'b0 == ap_block_pp0_stage0_subdone_grp16_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp5 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp6 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp7 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp9 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp9) & (1'b0 == ap_block_pp0_stage0_subdone_grp9_done_reg));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp16 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b1 == ap_block_state2_pp0_stage0_iter1_grp16) & (1'b0 == ap_block_pp0_stage0_subdone_grp16_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp15) & (1'b0 == ap_block_pp0_stage0_subdone_grp15_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp10) & (1'b0 == ap_block_pp0_stage0_subdone_grp10_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp9) & (1'b0 == ap_block_pp0_stage0_subdone_grp9_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp7) 
    & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_pp0_stage0_iter1_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp10 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp10) & (1'b0 == ap_block_pp0_stage0_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp11 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp11) & (1'b0 == ap_block_pp0_stage0_subdone_grp11_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp12 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp13 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp14 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp15 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp15) & (1'b0 == ap_block_pp0_stage0_subdone_grp15_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp16) & (1'b0 == ap_block_pp0_stage0_subdone_grp16_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp4 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp5 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp6 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp7 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp7) & (1'b0 == ap_block_pp0_stage0_subdone_grp7_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp8) & (1'b0 == ap_block_pp0_stage0_subdone_grp8_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp9 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp9) & (1'b0 == ap_block_pp0_stage0_subdone_grp9_done_reg));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((pe_streams_14_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd14));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp10 = ((pe_streams_5_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd5));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp11 = ((pe_streams_4_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd4));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp12 = ((pe_streams_3_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd3));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp13 = ((trunc_ln230_reg_265 == 4'd2) & (pe_streams_2_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp14 = ((trunc_ln230_reg_265 == 4'd1) & (pe_streams_1_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp15 = ((trunc_ln230_reg_265 == 4'd0) & (pe_streams_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp16 = ((trunc_ln230_reg_265 == 4'd15) & (pe_streams_15_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp2 = ((pe_streams_13_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd13));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp3 = ((pe_streams_12_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd12));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp4 = ((pe_streams_11_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd11));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp5 = ((pe_streams_10_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd10));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp6 = ((pe_streams_9_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd9));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp7 = ((pe_streams_8_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd8));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp8 = ((pe_streams_7_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd7));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp9 = ((pe_streams_6_full_n == 1'b0) & (trunc_ln230_reg_265 == 4'd6));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln230_fu_234_p2 = ((ap_sig_allocacmp_i_1 == 5'd16) ? 1'b1 : 1'b0);

assign pe_streams_0_din = 97'd79228162514264337593543950336;

assign pe_streams_10_din = 97'd79228162514264337593543950336;

assign pe_streams_11_din = 97'd79228162514264337593543950336;

assign pe_streams_12_din = 97'd79228162514264337593543950336;

assign pe_streams_13_din = 97'd79228162514264337593543950336;

assign pe_streams_14_din = 97'd79228162514264337593543950336;

assign pe_streams_15_din = 97'd79228162514264337593543950336;

assign pe_streams_1_din = 97'd79228162514264337593543950336;

assign pe_streams_2_din = 97'd79228162514264337593543950336;

assign pe_streams_3_din = 97'd79228162514264337593543950336;

assign pe_streams_4_din = 97'd79228162514264337593543950336;

assign pe_streams_5_din = 97'd79228162514264337593543950336;

assign pe_streams_6_din = 97'd79228162514264337593543950336;

assign pe_streams_7_din = 97'd79228162514264337593543950336;

assign pe_streams_8_din = 97'd79228162514264337593543950336;

assign pe_streams_9_din = 97'd79228162514264337593543950336;

assign trunc_ln230_fu_246_p1 = ap_sig_allocacmp_i_1[3:0];

endmodule //spmv_csc_distribute_to_pe_Pipeline_VITIS_LOOP_230_3
